declare const ANG1: number
declare const ANG2: number
declare const ANG10: number
declare const ANG15: number
declare const ANG20: number
declare const ANG30: number
declare const ANG60: number
declare const ANG105: number
declare const ANG210: number
declare const ANG255: number
declare const ANG340: number
declare const ANG350: number