declare const BT_WEAPONMASK: number
declare const BT_WEAPONNEXT: number
declare const BT_WEAPONPREV: number
declare const BT_ATTACK: number
declare const BT_SPIN: number
declare const BT_CAMLEFT: number
declare const BT_CAMRIGHT: number
declare const BT_TOSSFLAG: number
declare const BT_JUMP: number
declare const BT_FIRENORMAL: number
declare const BT_CUSTOM1: number
declare const BT_CUSTOM2: number
declare const BT_CUSTOM3: number