declare const CA_NONE: number
declare const CA_THOK: number
declare const CA_FLY: number
declare const CA_GLIDEANDCLIMB: number
declare const CA_HOMINGTHOK: number
declare const CA_SWIM: number
declare const CA_DOUBLEJUMP: number
declare const CA_FLOAT: number
declare const CA_SLOWFALL: number
declare const CA_TELEKINESIS: number
declare const CA_FALLSWITCH: number
declare const CA_JUMPBOOST: number
declare const CA_AIRDRILL: number
declare const CA_JUMPTHOK: number
declare const CA_BOUNCE: number
declare const CA_TWINSPIN: number