declare const CR_NONE: number
declare const CR_GENERIC: number
declare const CR_PLAYER: number
declare const CR_NIGHTSMODE: number
declare const CR_NIGHTSFALL: number
declare const CR_BRAKGOOP: number
declare const CR_ZOOMTUBE: number
declare const CR_ROPEHANG: number
declare const CR_MACESPIN: number
declare const CR_MINECART: number
declare const CR_ROLLOUT: number
declare const CR_PTERABYTE: number
declare const CR_DUSTDEVIL: number