declare const CV_SAVE: number
declare const CV_CALL: number
declare const CV_NETVAR: number
declare const CV_NOINIT: number
declare const CV_FLOAT: number
declare const CV_NOTINNET: number
declare const CV_MODIFIED: number
declare const CV_SHOWMODIF: number
declare const CV_SHOWMODIFONETIME: number
declare const CV_NOSHOWHELP: number
declare const CV_HIDDEN: number
declare const CV_HIDEN: number
declare const CV_CHEAT: number
declare const CV_NOLUA: number
