declare const DI_NODIR: number
declare const DI_EAST: number
declare const DI_NORTHEAST: number
declare const DI_NORTH: number
declare const DI_NORTHWEST: number
declare const DI_WEST: number
declare const DI_SOUTHWEST: number
declare const DI_SOUTH: number
declare const DI_SOUTHEAST: number
declare const NUMDIRS: number