declare const DMG_WATER: number
declare const DMG_FIRE: number
declare const DMG_ELECTRIC: number
declare const DMG_SPIKE: number
declare const DMG_NUKE: number
declare const DMG_INSTAKILL: number
declare const DMG_DROWNED: number
declare const DMG_SPACEDROWN: number
declare const DMG_DEATHPIT: number
declare const DMG_CRUSHED: number
declare const DMG_SPECTATOR: number
declare const DMG_CANHURTSELF: number
declare const DMG_DEATHMASK: number