declare const DSSPIN: number
declare const DSPUTPUT: number
declare const DSPUDPUD: number
declare const DSTHOK: number
declare const DSSPNDSH: number
declare const DSZOOM: number
declare const DSGASP: number
declare const DSJUMP: number
declare const DSSKID: number
declare const DSALTOW1: number
declare const DSALTOW2: number
declare const DSALTOW3: number
declare const DSALTOW4: number
declare const DSVICTR1: number
declare const DSVICTR2: number
declare const DSVICTR3: number
declare const DSVICTR4: number
declare const DSALTDI1: number
declare const DSALTDI2: number
declare const DSALTDI3: number
declare const DSALTDI4: number