declare const FF_FRAMEMASK: number
declare const FF_SPR2SUPER: number
declare const FF_SPR2ENDSTATE: number
declare const FF_SPR2MIDSTART: number
declare const FF_BLENDMASK: number
declare const FF_BLENDSHIFT: number
declare const FF_ADD: number
declare const FF_SUBTRACT: number
declare const FF_REVERSESUBTRACT: number
declare const FF_MODULATE: number
declare const FF_TRANSMASK: number
declare const FF_TRANSSHIFT: number
declare const FF_TRANS10: number
declare const FF_TRANS20: number
declare const FF_TRANS30: number
declare const FF_TRANS40: number
declare const FF_TRANS50: number
declare const FF_TRANS60: number
declare const FF_TRANS70: number
declare const FF_TRANS80: number
declare const FF_TRANS90: number
declare const FF_BRIGHTMASK: number
declare const FF_FULLBRIGHT: number
declare const FF_FULLDARK: number
declare const FF_SEMIBRIGHT: number
declare const FF_PAPERSPRITE: number
declare const FF_FLOORSPRITE: number
declare const FF_VERTICALFLIP: number
declare const FF_HORIZONTALFLIP: number
declare const FF_ANIMATE: number
declare const FF_GLOBALANIM: number
declare const FF_RANDOMANIM: number
declare const FF_EXISTS: number
declare const FF_BLOCKPLAYER: number
declare const FF_BLOCKOTHERS: number
declare const FF_SOLID: number
declare const FF_RENDERSIDES: number
declare const FF_RENDERPLANES: number
declare const FF_RENDERALL: number
declare const FF_SWIMMABLE: number
declare const FF_NOSHADE: number
declare const FF_CUTSOLIDS: number
declare const FF_CUTEXTRA: number
declare const FF_CUTLEVEL: number
declare const FF_CUTSPRITES: number
declare const FF_BOTHPLANES: number
declare const FF_EXTRA: number
declare const FF_TRANSLUCENT: number
declare const FF_FOG: number
declare const FF_INVERTPLANES: number
declare const FF_ALLSIDES: number
declare const FF_INVERTSIDES: number
declare const FF_DOUBLESHADOW: number
declare const FF_FLOATBOB: number
declare const FF_NORETURN: number
declare const FF_CRUMBLE: number
declare const FF_SHATTERBOTTOM: number
declare const FF_GOOWATER: number
declare const FF_MARIO: number
declare const FF_BUSTUP: number
declare const FF_QUICKSAND: number
declare const FF_PLATFORM: number
declare const FF_REVERSEPLATFORM: number
declare const FF_INTANGIBLEFLATS: number
declare const FF_SHATTER: number
declare const FF_SPINBUST: number
declare const FF_STRONGBUST: number
declare const FF_RIPPLE: number
declare const FF_COLORMAPONLY: number