declare const GC_NULL: number
declare const GC_FORWARD: number
declare const GC_BACKWARD: number
declare const GC_STRAFELEFT: number
declare const GC_STRAFERIGHT: number
declare const GC_TURNLEFT: number
declare const GC_TURNRIGHT: number
declare const GC_WEAPONNEXT: number
declare const GC_WEAPONPREV: number
declare const GC_WEPSLOT1: number
declare const GC_WEPSLOT2: number
declare const GC_WEPSLOT3: number
declare const GC_WEPSLOT4: number
declare const GC_WEPSLOT5: number
declare const GC_WEPSLOT6: number
declare const GC_WEPSLOT7: number
declare const GC_WEPSLOT8: number
declare const GC_WEPSLOT9: number
declare const GC_WEPSLOT10: number
declare const GC_FIRE: number
declare const GC_FIRENORMAL: number
declare const GC_TOSSFLAG: number
declare const GC_SPIN: number
declare const GC_CAMTOGGLE: number
declare const GC_CAMRESET: number
declare const GC_LOOKUP: number
declare const GC_LOOKDOWN: number
declare const GC_CENTERVIEW: number
declare const GC_MOUSEAIMING: number
declare const GC_TALKKEY: number
declare const GC_TEAMKEY: number
declare const GC_SCORES: number
declare const GC_JUMP: number
declare const GC_CONSOLE: number
declare const GC_PAUSE: number
declare const GC_SYSTEMMENU: number
declare const GC_SCREENSHOT: number
declare const GC_RECORDGIF: number
declare const GC_VIEWPOINT: number
declare const GC_CUSTOM1: number
declare const GC_CUSTOM2: number
declare const GC_CUSTOM3: number
declare const NUM_GAMECONTROLS: number