declare const GS_NULL: number
declare const GS_LEVEL: number
declare const GS_INTERMISSION: number
declare const GS_CONTINUING: number
declare const GS_TITLESCREEN: number
declare const GS_TIMEATTACK: number
declare const GS_CREDITS: number
declare const GS_EVALUATION: number
declare const GS_GAMEEND: number
declare const GS_INTRO: number
declare const GS_ENDING: number
declare const GS_CUTSCENE: number
declare const GS_DEDICATEDSERVER: number
declare const GS_WAITINGPLAYERS: number