declare const HUD_LIVES: number
declare const HUD_RINGS: number
declare const HUD_RINGSNUM: number
declare const HUD_RINGSNUMTICS: number
declare const HUD_SCORE: number
declare const HUD_SCORENUM: number
declare const HUD_TIME: number
declare const HUD_MINUTES: number
declare const HUD_TIMECOLON: number
declare const HUD_SECONDS: number
declare const HUD_TIMETICCOLON: number
declare const HUD_TICS: number
declare const HUD_HUNTPICS: number
declare const HUD_POWERUPS: number

declare const HUD_SS_TOTALRINGS: number
declare const HUD_GETRINGS: number
declare const HUD_GETRINGSNUM: number
declare const HUD_TIMELEFT: number
declare const HUD_TIMELEFTNUM: number
declare const HUD_TIMEUP: number