declare const INT8_MIN: number
declare const INT16_MIN: number
declare const INT32_MIN: number
declare const INT8_MAX: number
declare const INT16_MAX: number
declare const INT32_MAX: number
declare const UINT8_MAX: number
declare const UINT16_MAX: number
declare const UINT32_MAX: number
