declare const JA_NONE: number
declare const JA_TURN: number
declare const JA_MOVE: number
declare const JA_LOOK: number
declare const JA_STRAFE: number
declare const JA_DIGITAL: number
declare const JA_JUMP: number
declare const JA_SPIN: number
declare const JA_FIRE: number
declare const JA_FIRENORMAL: number