declare const JT_NONE: number
declare const JT_OTHER: number
declare const JT_MASTER: number
declare const JT_1UP: number
declare const JT_SHOES: number
declare const JT_INV: number
declare const JT_MINV: number
declare const JT_DROWN: number
declare const JT_SUPER: number
declare const JT_GOVER: number
declare const JT_NIGHTSTIMEOUT: number
declare const JT_SSTIMEOUT: number