declare const LE_AXE: number
declare const LE_KOOPA: number
declare const LE_CAPSULE0: number
declare const LE_CAPSULE1: number
declare const LE_CAPSULE2: number
declare const LE_BRAKPLATFORM: number
declare const LE_TURRET: number
declare const LE_BRAKVILEATACK: number
declare const LE_BOSS4DROP: number
declare const LE_BOSSDEAD: number
declare const LE_ALLBOSSESDEAD: number
declare const LE_PINCHPHASE: number
declare const LE_PARAMWIDTH: number