declare const LF_SCRIPTISFILE: number
declare const LF_SPEEDMUSIC: number
declare const LF_NOSSMUSIC: number
declare const LF_NORELOAD: number
declare const LF_NOZONE: number
declare const LF_SAVEGAME: number
declare const LF_MIXNIGHTSCOUNTDOWN: number
declare const LF_WARNINGTITLE: number
declare const LF_NOTITLECARD: number