declare const MB_BUTTON1: number
declare const MB_BUTTON2: number
declare const MB_BUTTON3: number
declare const MB_BUTTON4: number
declare const MB_BUTTON5: number
declare const MB_BUTTON6: number
declare const MB_BUTTON7: number
declare const MB_BUTTON8: number
declare const MB_SCROLLUP: number
declare const MB_SCROLLDOWN: number