declare const MF_SPECIAL: number
declare const MF_SOLID: number
declare const MF_SHOOTABLE: number
declare const MF_NOSECTOR: number
declare const MF_NOBLOCKMAP: number
declare const MF_PAPERCOLLISION: number
declare const MF_PUSHABLE: number
declare const MF_BOSS: number
declare const MF_SPAWNCEILING: number
declare const MF_NOGRAVITY: number
declare const MF_AMBIENT: number
declare const MF_SLIDEME: number
declare const MF_NOCLIP: number
declare const MF_FLOAT: number
declare const MF_BOXICON: number
declare const MF_MISSILE: number
declare const MF_SPRING: number
declare const MF_BOUNCE: number
declare const MF_MONITOR: number
declare const MF_NOTHINK: number
declare const MF_FIRE: number
declare const MF_NOCLIPHEIGHT: number
declare const MF_ENEMY: number
declare const MF_SCENERY: number
declare const MF_PAIN: number
declare const MF_STICKY: number
declare const MF_NIGHTSITEM: number
declare const MF_NOCLIPTHING: number
declare const MF_GRENADEBOUNCE: number
declare const MF_RUNSPAWNFUNC: number