declare const MF2_AXIS: number
declare const MF2_TWOD: number
declare const MF2_DONTRESPAWN: number
declare const MF2_DONTDRAW: number
declare const MF2_AUTOMATIC: number
declare const MF2_RAILRING: number
declare const MF2_BOUNCERING: number
declare const MF2_EXPLOSION: number
declare const MF2_SCATTER: number
declare const MF2_BEYONDTHEGRAVE: number
declare const MF2_SLIDEPUSH: number
declare const MF2_CLASSICPUSH: number
declare const MF2_INVERTAIMABLE: number
declare const MF2_INFLOAT: number
declare const MF2_DEBRIS: number
declare const MF2_NIGHTSPULL: number
declare const MF2_JUSTATTACKED: number
declare const MF2_FIRING: number
declare const MF2_SUPERFIRE: number
declare const MF2_SHADOW: number
declare const MF2_STRONGBOX: number
declare const MF2_OBJECTFLIP: number
declare const MF2_SKULLFLY: number
declare const MF2_FRET: number
declare const MF2_BOSSNOTRAP: number
declare const MF2_BOSSFLEE: number
declare const MF2_BOSSDEAD: number
declare const MF2_AMBUSH: number
declare const MF2_LINKDRAW: number
declare const MF2_SHIELD: number
declare const MF2_SPLAT: number