declare const MFE_ONGROUND: number
declare const MFE_JUSTHITFLOOR: number
declare const MFE_TOUCHWATER: number
declare const MFE_UNDERWATER: number
declare const MFE_JUSTSTEPPEDDOWN: number
declare const MFE_VERTICALFLIP: number
declare const MFE_GOOWATER: number
declare const MFE_TOUCHLAVA: number
declare const MFE_PUSHED: number
declare const MFE_SPRUNG: number
declare const MFE_APPLYPMOMZ: number
declare const MFE_TRACERANGLE: number