declare const FRACUNIT: number
declare const FU: number
declare const FRACBITS: number
declare const TICRATE: number
declare const NEWTICRATERATIO: number
declare const NEWTICRATE: number
declare const MUSICRATE: number
declare const RING_DIST: number
declare const PUSHACCEL: number
declare const MODID: number
declare const MODVERSION: number
declare const CODEBASE: number
declare const VERSION: number
declare const VERSIONSTRING: string
declare const SUBVERSION: number
declare const FLOATSPEED: number
declare const MAXSTEPMOVE: number
declare const USERANGE: number
declare const MELEERANGE: number
declare const MISSILERANGE: number
declare const ONFLOORZ: number
declare const ONCEILINGZ: number
declare const INFLIVES: number
declare const JOYAXISRANGE: number
