declare const ML_IMPASSIBLE: number
declare const ML_BLOCKMONSTERS: number
declare const ML_TWOSIDED: number
declare const ML_DONTPEGTOP: number
declare const ML_DONTPEGBOTTOM: number
declare const ML_EFFECT1: number
declare const ML_NOCLIMB: number
declare const ML_EFFECT2: number
declare const ML_EFFECT3: number
declare const ML_EFFECT4: number
declare const ML_EFFECT5: number
declare const ML_NETONLY: number
declare const ML_NONET: number
declare const ML_EFFECT6: number
declare const ML_BOUNCY: number
declare const ML_TFERLINE: number