declare const MT_NULL: number
declare const MT_UNKNOWN: number
declare const MT_THOK: number
declare const MT_PLAYER: number
declare const MT_TAILSOVERLAY: number
declare const MT_METALJETFUME: number
declare const MT_BLUECRAWLA: number
declare const MT_REDCRAWLA: number
declare const MT_GFZFISH: number
declare const MT_GOLDBUZZ: number
declare const MT_REDBUZZ: number
declare const MT_JETTBOMBER: number
declare const MT_JETTGUNNER: number
declare const MT_CRAWLACOMMANDER: number
declare const MT_DETON: number
declare const MT_SKIM: number
declare const MT_TURRET: number
declare const MT_POPUPTURRET: number
declare const MT_SPINCUSHION: number
declare const MT_CRUSHSTACEAN: number
declare const MT_CRUSHCLAW: number
declare const MT_CRUSHCHAIN: number
declare const MT_BANPYURA: number
declare const MT_BANPSPRING: number
declare const MT_JETJAW: number
declare const MT_SNAILER: number
declare const MT_VULTURE: number
declare const MT_POINTY: number
declare const MT_POINTYBALL: number
declare const MT_ROBOHOOD: number
declare const MT_FACESTABBER: number
declare const MT_FACESTABBERSPEAR: number
declare const MT_EGGGUARD: number
declare const MT_EGGSHIELD: number
declare const MT_GSNAPPER: number
declare const MT_SNAPPER_LEG: number
declare const MT_SNAPPER_HEAD: number
declare const MT_MINUS: number
declare const MT_MINUSDIRT: number
declare const MT_SPRINGSHELL: number
declare const MT_YELLOWSHELL: number
declare const MT_UNIDUS: number
declare const MT_UNIBALL: number
declare const MT_CANARIVORE: number
declare const MT_CANARIVORE_GAS: number
declare const MT_PYREFLY: number
declare const MT_PYREFLY_FIRE: number
declare const MT_PTERABYTESPAWNER: number
declare const MT_PTERABYTEWAYPOINT: number
declare const MT_PTERABYTE: number
declare const MT_DRAGONBOMBER: number
declare const MT_DRAGONWING: number
declare const MT_DRAGONTAIL: number
declare const MT_DRAGONMINE: number
declare const MT_BOSSEXPLODE: number
declare const MT_SONIC3KBOSSEXPLODE: number
declare const MT_BOSSFLYPOINT: number
declare const MT_EGGTRAP: number
declare const MT_BOSS3WAYPOINT: number
declare const MT_BOSS9GATHERPOINT: number
declare const MT_BOSSJUNK: number
declare const MT_EGGMOBILE: number
declare const MT_JETFUME1: number
declare const MT_EGGMOBILE_BALL: number
declare const MT_EGGMOBILE_TARGET: number
declare const MT_EGGMOBILE_FIRE: number
declare const MT_EGGMOBILE2: number
declare const MT_EGGMOBILE2_POGO: number
declare const MT_GOOP: number
declare const MT_GOOPTRAIL: number
declare const MT_EGGMOBILE3: number
declare const MT_FAKEMOBILE: number
declare const MT_SHOCKWAVE: number
declare const MT_EGGMOBILE4: number
declare const MT_EGGMOBILE4_MACE: number
declare const MT_JETFLAME: number
declare const MT_EGGROBO1: number
declare const MT_EGGROBO1JET: number
declare const MT_FANG: number
declare const MT_BROKENROBOT: number
declare const MT_VWREF: number
declare const MT_VWREB: number
declare const MT_PROJECTORLIGHT: number
declare const MT_FBOMB: number
declare const MT_TNTDUST: number
declare const MT_FSGNA: number
declare const MT_FSGNB: number
declare const MT_FANGWAYPOINT: number
declare const MT_BLACKEGGMAN: number
declare const MT_BLACKEGGMAN_HELPER: number
declare const MT_BLACKEGGMAN_GOOPFIRE: number
declare const MT_BLACKEGGMAN_MISSILE: number
declare const MT_CYBRAKDEMON: number
declare const MT_CYBRAKDEMON_ELECTRIC_BARRIER: number
declare const MT_CYBRAKDEMON_MISSILE: number
declare const MT_CYBRAKDEMON_FLAMESHOT: number
declare const MT_CYBRAKDEMON_FLAMEREST: number
declare const MT_CYBRAKDEMON_TARGET_RETICULE: number
declare const MT_CYBRAKDEMON_TARGET_DOT: number
declare const MT_CYBRAKDEMON_NAPALM_BOMB_LARGE: number
declare const MT_CYBRAKDEMON_NAPALM_BOMB_SMALL: number
declare const MT_CYBRAKDEMON_NAPALM_FLAMES: number
declare const MT_CYBRAKDEMON_VILE_EXPLOSION: number
declare const MT_METALSONIC_RACE: number
declare const MT_METALSONIC_BATTLE: number
declare const MT_MSSHIELD_FRONT: number
declare const MT_MSGATHER: number
declare const MT_RING: number
declare const MT_FLINGRING: number
declare const MT_BLUESPHERE: number
declare const MT_FLINGBLUESPHERE: number
declare const MT_BOMBSPHERE: number
declare const MT_REDTEAMRING: number
declare const MT_BLUETEAMRING: number
declare const MT_TOKEN: number
declare const MT_REDFLAG: number
declare const MT_BLUEFLAG: number
declare const MT_EMBLEM: number
declare const MT_EMERALD1: number
declare const MT_EMERALD2: number
declare const MT_EMERALD3: number
declare const MT_EMERALD4: number
declare const MT_EMERALD5: number
declare const MT_EMERALD6: number
declare const MT_EMERALD7: number
declare const MT_EMERHUNT: number
declare const MT_EMERALDSPAWN: number
declare const MT_FLINGEMERALD: number
declare const MT_FAN: number
declare const MT_STEAM: number
declare const MT_BUMPER: number
declare const MT_BALLOON: number
declare const MT_YELLOWSPRING: number
declare const MT_REDSPRING: number
declare const MT_BLUESPRING: number
declare const MT_YELLOWDIAG: number
declare const MT_REDDIAG: number
declare const MT_BLUEDIAG: number
declare const MT_YELLOWHORIZ: number
declare const MT_REDHORIZ: number
declare const MT_BLUEHORIZ: number
declare const MT_BOOSTERSEG: number
declare const MT_BOOSTERROLLER: number
declare const MT_YELLOWBOOSTER: number
declare const MT_REDBOOSTER: number
declare const MT_BUBBLES: number
declare const MT_SIGN: number
declare const MT_SPIKEBALL: number
declare const MT_SPINFIRE: number
declare const MT_SPIKE: number
declare const MT_WALLSPIKE: number
declare const MT_WALLSPIKEBASE: number
declare const MT_STARPOST: number
declare const MT_BIGMINE: number
declare const MT_BLASTEXECUTOR: number
declare const MT_CANNONLAUNCHER: number
declare const MT_BOXSPARKLE: number
declare const MT_RING_BOX: number
declare const MT_PITY_BOX: number
declare const MT_ATTRACT_BOX: number
declare const MT_FORCE_BOX: number
declare const MT_ARMAGEDDON_BOX: number
declare const MT_WHIRLWIND_BOX: number
declare const MT_ELEMENTAL_BOX: number
declare const MT_SNEAKERS_BOX: number
declare const MT_INVULN_BOX: number
declare const MT_1UP_BOX: number
declare const MT_EGGMAN_BOX: number
declare const MT_MIXUP_BOX: number
declare const MT_MYSTERY_BOX: number
declare const MT_GRAVITY_BOX: number
declare const MT_RECYCLER_BOX: number
declare const MT_SCORE1K_BOX: number
declare const MT_SCORE10K_BOX: number
declare const MT_FLAMEAURA_BOX: number
declare const MT_BUBBLEWRAP_BOX: number
declare const MT_THUNDERCOIN_BOX: number
declare const MT_PITY_GOLDBOX: number
declare const MT_ATTRACT_GOLDBOX: number
declare const MT_FORCE_GOLDBOX: number
declare const MT_ARMAGEDDON_GOLDBOX: number
declare const MT_WHIRLWIND_GOLDBOX: number
declare const MT_ELEMENTAL_GOLDBOX: number
declare const MT_SNEAKERS_GOLDBOX: number
declare const MT_INVULN_GOLDBOX: number
declare const MT_EGGMAN_GOLDBOX: number
declare const MT_GRAVITY_GOLDBOX: number
declare const MT_FLAMEAURA_GOLDBOX: number
declare const MT_BUBBLEWRAP_GOLDBOX: number
declare const MT_THUNDERCOIN_GOLDBOX: number
declare const MT_RING_REDBOX: number
declare const MT_RING_BLUEBOX: number
declare const MT_RING_ICON: number
declare const MT_PITY_ICON: number
declare const MT_ATTRACT_ICON: number
declare const MT_FORCE_ICON: number
declare const MT_ARMAGEDDON_ICON: number
declare const MT_WHIRLWIND_ICON: number
declare const MT_ELEMENTAL_ICON: number
declare const MT_SNEAKERS_ICON: number
declare const MT_INVULN_ICON: number
declare const MT_1UP_ICON: number
declare const MT_EGGMAN_ICON: number
declare const MT_MIXUP_ICON: number
declare const MT_GRAVITY_ICON: number
declare const MT_RECYCLER_ICON: number
declare const MT_SCORE1K_ICON: number
declare const MT_SCORE10K_ICON: number
declare const MT_FLAMEAURA_ICON: number
declare const MT_BUBBLEWRAP_ICON: number
declare const MT_THUNDERCOIN_ICON: number
declare const MT_ROCKET: number
declare const MT_LASER: number
declare const MT_TORPEDO: number
declare const MT_TORPEDO2: number
declare const MT_ENERGYBALL: number
declare const MT_MINE: number
declare const MT_JETTBULLET: number
declare const MT_TURRETLASER: number
declare const MT_CANNONBALL: number
declare const MT_CANNONBALLDECOR: number
declare const MT_ARROW: number
declare const MT_DEMONFIRE: number
declare const MT_LETTER: number
declare const MT_TUTORIALPLANT: number
declare const MT_TUTORIALLEAF: number
declare const MT_TUTORIALFLOWER: number
declare const MT_TUTORIALFLOWERF: number
declare const MT_GFZFLOWER1: number
declare const MT_GFZFLOWER2: number
declare const MT_GFZFLOWER3: number
declare const MT_BLUEBERRYBUSH: number
declare const MT_BERRYBUSH: number
declare const MT_BUSH: number
declare const MT_GFZTREE: number
declare const MT_GFZBERRYTREE: number
declare const MT_GFZCHERRYTREE: number
declare const MT_CHECKERTREE: number
declare const MT_CHECKERSUNSETTREE: number
declare const MT_FHZTREE: number
declare const MT_FHZPINKTREE: number
declare const MT_POLYGONTREE: number
declare const MT_BUSHTREE: number
declare const MT_BUSHREDTREE: number
declare const MT_SPRINGTREE: number
declare const MT_THZFLOWER1: number
declare const MT_THZFLOWER2: number
declare const MT_THZFLOWER3: number
declare const MT_THZTREE: number
declare const MT_THZTREEBRANCH: number
declare const MT_ALARM: number
declare const MT_GARGOYLE: number
declare const MT_BIGGARGOYLE: number
declare const MT_SEAWEED: number
declare const MT_WATERDRIP: number
declare const MT_WATERDROP: number
declare const MT_CORAL1: number
declare const MT_CORAL2: number
declare const MT_CORAL3: number
declare const MT_CORAL4: number
declare const MT_CORAL5: number
declare const MT_BLUECRYSTAL: number
declare const MT_KELP: number
declare const MT_ANIMALGAETOP: number
declare const MT_ANIMALGAESEG: number
declare const MT_DSZSTALAGMITE: number
declare const MT_DSZ2STALAGMITE: number
declare const MT_LIGHTBEAM: number
declare const MT_CHAIN: number
declare const MT_FLAME: number
declare const MT_FLAMEPARTICLE: number
declare const MT_EGGSTATUE: number
declare const MT_MACEPOINT: number
declare const MT_CHAINMACEPOINT: number
declare const MT_SPRINGBALLPOINT: number
declare const MT_CHAINPOINT: number
declare const MT_HIDDEN_SLING: number
declare const MT_FIREBARPOINT: number
declare const MT_CUSTOMMACEPOINT: number
declare const MT_SMALLMACECHAIN: number
declare const MT_BIGMACECHAIN: number
declare const MT_SMALLMACE: number
declare const MT_BIGMACE: number
declare const MT_SMALLGRABCHAIN: number
declare const MT_BIGGRABCHAIN: number
declare const MT_YELLOWSPRINGBALL: number
declare const MT_REDSPRINGBALL: number
declare const MT_SMALLFIREBAR: number
declare const MT_BIGFIREBAR: number
declare const MT_CEZFLOWER: number
declare const MT_CEZPOLE1: number
declare const MT_CEZPOLE2: number
declare const MT_CEZBANNER1: number
declare const MT_CEZBANNER2: number
declare const MT_PINETREE: number
declare const MT_CEZBUSH1: number
declare const MT_CEZBUSH2: number
declare const MT_CANDLE: number
declare const MT_CANDLEPRICKET: number
declare const MT_FLAMEHOLDER: number
declare const MT_FIRETORCH: number
declare const MT_WAVINGFLAG1: number
declare const MT_WAVINGFLAG2: number
declare const MT_WAVINGFLAGSEG1: number
declare const MT_WAVINGFLAGSEG2: number
declare const MT_CRAWLASTATUE: number
declare const MT_FACESTABBERSTATUE: number
declare const MT_SUSPICIOUSFACESTABBERSTATUE: number
declare const MT_BRAMBLES: number
declare const MT_BIGTUMBLEWEED: number
declare const MT_LITTLETUMBLEWEED: number
declare const MT_CACTI1: number
declare const MT_CACTI2: number
declare const MT_CACTI3: number
declare const MT_CACTI4: number
declare const MT_CACTI5: number
declare const MT_CACTI6: number
declare const MT_CACTI7: number
declare const MT_CACTI8: number
declare const MT_CACTI9: number
declare const MT_CACTI10: number
declare const MT_CACTI11: number
declare const MT_CACTITINYSEG: number
declare const MT_CACTISMALLSEG: number
declare const MT_ARIDSIGN_CAUTION: number
declare const MT_ARIDSIGN_CACTI: number
declare const MT_ARIDSIGN_SHARPTURN: number
declare const MT_OILLAMP: number
declare const MT_TNTBARREL: number
declare const MT_PROXIMITYTNT: number
declare const MT_DUSTDEVIL: number
declare const MT_DUSTLAYER: number
declare const MT_ARIDDUST: number
declare const MT_MINECART: number
declare const MT_MINECARTSEG: number
declare const MT_MINECARTSPAWNER: number
declare const MT_MINECARTEND: number
declare const MT_MINECARTENDSOLID: number
declare const MT_MINECARTSIDEMARK: number
declare const MT_MINECARTSPARK: number
declare const MT_SALOONDOOR: number
declare const MT_SALOONDOORCENTER: number
declare const MT_TRAINCAMEOSPAWNER: number
declare const MT_TRAINSEG: number
declare const MT_TRAINDUSTSPAWNER: number
declare const MT_TRAINSTEAMSPAWNER: number
declare const MT_MINECARTSWITCHPOINT: number
declare const MT_FLAMEJET: number
declare const MT_VERTICALFLAMEJET: number
declare const MT_FLAMEJETFLAME: number
declare const MT_FJSPINAXISA: number
declare const MT_FJSPINAXISB: number
declare const MT_FLAMEJETFLAMEB: number
declare const MT_LAVAFALL: number
declare const MT_LAVAFALL_LAVA: number
declare const MT_LAVAFALLROCK: number
declare const MT_ROLLOUTSPAWN: number
declare const MT_ROLLOUTROCK: number
declare const MT_BIGFERNLEAF: number
declare const MT_BIGFERN: number
declare const MT_JUNGLEPALM: number
declare const MT_TORCHFLOWER: number
declare const MT_WALLVINE_LONG: number
declare const MT_WALLVINE_SHORT: number
declare const MT_GLAREGOYLE: number
declare const MT_GLAREGOYLEUP: number
declare const MT_GLAREGOYLEDOWN: number
declare const MT_GLAREGOYLELONG: number
declare const MT_TARGET: number
declare const MT_GREENFLAME: number
declare const MT_BLUEGARGOYLE: number
declare const MT_STALAGMITE0: number
declare const MT_STALAGMITE1: number
declare const MT_STALAGMITE2: number
declare const MT_STALAGMITE3: number
declare const MT_STALAGMITE4: number
declare const MT_STALAGMITE5: number
declare const MT_STALAGMITE6: number
declare const MT_STALAGMITE7: number
declare const MT_STALAGMITE8: number
declare const MT_STALAGMITE9: number
declare const MT_XMASPOLE: number
declare const MT_CANDYCANE: number
declare const MT_SNOWMAN: number
declare const MT_SNOWMANHAT: number
declare const MT_LAMPPOST1: number
declare const MT_LAMPPOST2: number
declare const MT_HANGSTAR: number
declare const MT_MISTLETOE: number
declare const MT_XMASBLUEBERRYBUSH: number
declare const MT_XMASBERRYBUSH: number
declare const MT_XMASBUSH: number
declare const MT_FHZICE1: number
declare const MT_FHZICE2: number
declare const MT_ROSY: number
declare const MT_CDLHRT: number
declare const MT_JACKO1: number
declare const MT_JACKO2: number
declare const MT_JACKO3: number
declare const MT_HHZTREE_TOP: number
declare const MT_HHZTREE_PART: number
declare const MT_HHZSHROOM: number
declare const MT_HHZGRASS: number
declare const MT_HHZTENTACLE1: number
declare const MT_HHZTENTACLE2: number
declare const MT_HHZSTALAGMITE_TALL: number
declare const MT_HHZSTALAGMITE_SHORT: number
declare const MT_BSZTALLFLOWER_RED: number
declare const MT_BSZTALLFLOWER_PURPLE: number
declare const MT_BSZTALLFLOWER_BLUE: number
declare const MT_BSZTALLFLOWER_CYAN: number
declare const MT_BSZTALLFLOWER_YELLOW: number
declare const MT_BSZTALLFLOWER_ORANGE: number
declare const MT_BSZFLOWER_RED: number
declare const MT_BSZFLOWER_PURPLE: number
declare const MT_BSZFLOWER_BLUE: number
declare const MT_BSZFLOWER_CYAN: number
declare const MT_BSZFLOWER_YELLOW: number
declare const MT_BSZFLOWER_ORANGE: number
declare const MT_BSZSHORTFLOWER_RED: number
declare const MT_BSZSHORTFLOWER_PURPLE: number
declare const MT_BSZSHORTFLOWER_BLUE: number
declare const MT_BSZSHORTFLOWER_CYAN: number
declare const MT_BSZSHORTFLOWER_YELLOW: number
declare const MT_BSZSHORTFLOWER_ORANGE: number
declare const MT_BSZTULIP_RED: number
declare const MT_BSZTULIP_PURPLE: number
declare const MT_BSZTULIP_BLUE: number
declare const MT_BSZTULIP_CYAN: number
declare const MT_BSZTULIP_YELLOW: number
declare const MT_BSZTULIP_ORANGE: number
declare const MT_BSZCLUSTER_RED: number
declare const MT_BSZCLUSTER_PURPLE: number
declare const MT_BSZCLUSTER_BLUE: number
declare const MT_BSZCLUSTER_CYAN: number
declare const MT_BSZCLUSTER_YELLOW: number
declare const MT_BSZCLUSTER_ORANGE: number
declare const MT_BSZBUSH_RED: number
declare const MT_BSZBUSH_PURPLE: number
declare const MT_BSZBUSH_BLUE: number
declare const MT_BSZBUSH_CYAN: number
declare const MT_BSZBUSH_YELLOW: number
declare const MT_BSZBUSH_ORANGE: number
declare const MT_BSZVINE_RED: number
declare const MT_BSZVINE_PURPLE: number
declare const MT_BSZVINE_BLUE: number
declare const MT_BSZVINE_CYAN: number
declare const MT_BSZVINE_YELLOW: number
declare const MT_BSZVINE_ORANGE: number
declare const MT_BSZSHRUB: number
declare const MT_BSZCLOVER: number
declare const MT_BIG_PALMTREE_TRUNK: number
declare const MT_BIG_PALMTREE_TOP: number
declare const MT_PALMTREE_TRUNK: number
declare const MT_PALMTREE_TOP: number
declare const MT_DBALL: number
declare const MT_EGGSTATUE2: number
declare const MT_ELEMENTAL_ORB: number
declare const MT_ATTRACT_ORB: number
declare const MT_FORCE_ORB: number
declare const MT_ARMAGEDDON_ORB: number
declare const MT_WHIRLWIND_ORB: number
declare const MT_PITY_ORB: number
declare const MT_FLAMEAURA_ORB: number
declare const MT_BUBBLEWRAP_ORB: number
declare const MT_THUNDERCOIN_ORB: number
declare const MT_THUNDERCOIN_SPARK: number
declare const MT_IVSP: number
declare const MT_SUPERSPARK: number
declare const MT_FLICKY_01: number
declare const MT_FLICKY_01_CENTER: number
declare const MT_FLICKY_02: number
declare const MT_FLICKY_02_CENTER: number
declare const MT_FLICKY_03: number
declare const MT_FLICKY_03_CENTER: number
declare const MT_FLICKY_04: number
declare const MT_FLICKY_04_CENTER: number
declare const MT_FLICKY_05: number
declare const MT_FLICKY_05_CENTER: number
declare const MT_FLICKY_06: number
declare const MT_FLICKY_06_CENTER: number
declare const MT_FLICKY_07: number
declare const MT_FLICKY_07_CENTER: number
declare const MT_FLICKY_08: number
declare const MT_FLICKY_08_CENTER: number
declare const MT_FLICKY_09: number
declare const MT_FLICKY_09_CENTER: number
declare const MT_FLICKY_10: number
declare const MT_FLICKY_10_CENTER: number
declare const MT_FLICKY_11: number
declare const MT_FLICKY_11_CENTER: number
declare const MT_FLICKY_12: number
declare const MT_FLICKY_12_CENTER: number
declare const MT_FLICKY_13: number
declare const MT_FLICKY_13_CENTER: number
declare const MT_FLICKY_14: number
declare const MT_FLICKY_14_CENTER: number
declare const MT_FLICKY_15: number
declare const MT_FLICKY_15_CENTER: number
declare const MT_FLICKY_16: number
declare const MT_FLICKY_16_CENTER: number
declare const MT_SECRETFLICKY_01: number
declare const MT_SECRETFLICKY_01_CENTER: number
declare const MT_SECRETFLICKY_02: number
declare const MT_SECRETFLICKY_02_CENTER: number
declare const MT_SEED: number
declare const MT_RAIN: number
declare const MT_SNOWFLAKE: number
declare const MT_SPLISH: number
declare const MT_LAVASPLISH: number
declare const MT_SMOKE: number
declare const MT_SMALLBUBBLE: number
declare const MT_MEDIUMBUBBLE: number
declare const MT_EXTRALARGEBUBBLE: number
declare const MT_WATERZAP: number
declare const MT_SPINDUST: number
declare const MT_TFOG: number
declare const MT_PARTICLE: number
declare const MT_PARTICLEGEN: number
declare const MT_SCORE: number
declare const MT_DROWNNUMBERS: number
declare const MT_GOTEMERALD: number
declare const MT_LOCKON: number
declare const MT_LOCKONINF: number
declare const MT_TAG: number
declare const MT_GOTFLAG: number
declare const MT_FINISHFLAG: number
declare const MT_AWATERA: number
declare const MT_AWATERB: number
declare const MT_AWATERC: number
declare const MT_AWATERD: number
declare const MT_AWATERE: number
declare const MT_AWATERF: number
declare const MT_AWATERG: number
declare const MT_AWATERH: number
declare const MT_RANDOMAMBIENT: number
declare const MT_RANDOMAMBIENT2: number
declare const MT_MACHINEAMBIENCE: number
declare const MT_CORK: number
declare const MT_LHRT: number
declare const MT_REDRING: number
declare const MT_BOUNCERING: number
declare const MT_RAILRING: number
declare const MT_INFINITYRING: number
declare const MT_AUTOMATICRING: number
declare const MT_EXPLOSIONRING: number
declare const MT_SCATTERRING: number
declare const MT_GRENADERING: number
declare const MT_BOUNCEPICKUP: number
declare const MT_RAILPICKUP: number
declare const MT_AUTOPICKUP: number
declare const MT_EXPLODEPICKUP: number
declare const MT_SCATTERPICKUP: number
declare const MT_GRENADEPICKUP: number
declare const MT_THROWNBOUNCE: number
declare const MT_THROWNINFINITY: number
declare const MT_THROWNAUTOMATIC: number
declare const MT_THROWNSCATTER: number
declare const MT_THROWNEXPLOSION: number
declare const MT_THROWNGRENADE: number
declare const MT_COIN: number
declare const MT_FLINGCOIN: number
declare const MT_GOOMBA: number
declare const MT_BLUEGOOMBA: number
declare const MT_FIREFLOWER: number
declare const MT_FIREBALL: number
declare const MT_FIREBALLTRAIL: number
declare const MT_SHELL: number
declare const MT_PUMA: number
declare const MT_PUMATRAIL: number
declare const MT_HAMMER: number
declare const MT_KOOPA: number
declare const MT_KOOPAFLAME: number
declare const MT_AXE: number
declare const MT_MARIOBUSH1: number
declare const MT_MARIOBUSH2: number
declare const MT_TOAD: number
declare const MT_AXIS: number
declare const MT_AXISTRANSFER: number
declare const MT_AXISTRANSFERLINE: number
declare const MT_NIGHTSDRONE: number
declare const MT_NIGHTSDRONE_MAN: number
declare const MT_NIGHTSDRONE_SPARKLING: number
declare const MT_NIGHTSDRONE_GOAL: number
declare const MT_NIGHTSPARKLE: number
declare const MT_NIGHTSLOOPHELPER: number
declare const MT_NIGHTSBUMPER: number
declare const MT_HOOP: number
declare const MT_HOOPCOLLIDE: number
declare const MT_HOOPCENTER: number
declare const MT_NIGHTSCORE: number
declare const MT_NIGHTSCHIP: number
declare const MT_FLINGNIGHTSCHIP: number
declare const MT_NIGHTSSTAR: number
declare const MT_FLINGNIGHTSSTAR: number
declare const MT_NIGHTSSUPERLOOP: number
declare const MT_NIGHTSDRILLREFILL: number
declare const MT_NIGHTSHELPER: number
declare const MT_NIGHTSEXTRATIME: number
declare const MT_NIGHTSLINKFREEZE: number
declare const MT_EGGCAPSULE: number
declare const MT_IDEYAANCHOR: number
declare const MT_NIGHTOPIANHELPER: number
declare const MT_PIAN: number
declare const MT_SHLEEP: number
declare const MT_PENGUINATOR: number
declare const MT_POPHAT: number
declare const MT_POPSHOT: number
declare const MT_POPSHOT_TRAIL: number
declare const MT_HIVEELEMENTAL: number
declare const MT_BUMBLEBORE: number
declare const MT_BUGGLE: number
declare const MT_SMASHINGSPIKEBALL: number
declare const MT_CACOLANTERN: number
declare const MT_CACOSHARD: number
declare const MT_CACOFIRE: number
declare const MT_SPINBOBERT: number
declare const MT_SPINBOBERT_FIRE1: number
declare const MT_SPINBOBERT_FIRE2: number
declare const MT_HANGSTER: number
declare const MT_TELEPORTMAN: number
declare const MT_ALTVIEWMAN: number
declare const MT_CRUMBLEOBJ: number
declare const MT_TUBEWAYPOINT: number
declare const MT_PUSH: number
declare const MT_PULL: number
declare const MT_GHOST: number
declare const MT_OVERLAY: number
declare const MT_ANGLEMAN: number
declare const MT_POLYANCHOR: number
declare const MT_POLYSPAWN: number
declare const MT_SKYBOX: number
declare const MT_SPARK: number
declare const MT_EXPLODE: number
declare const MT_UWEXPLODE: number
declare const MT_DUST: number
declare const MT_ROCKSPAWNER: number
declare const MT_FALLINGROCK: number
declare const MT_ROCKCRUMBLE1: number
declare const MT_ROCKCRUMBLE2: number
declare const MT_ROCKCRUMBLE3: number
declare const MT_ROCKCRUMBLE4: number
declare const MT_ROCKCRUMBLE5: number
declare const MT_ROCKCRUMBLE6: number
declare const MT_ROCKCRUMBLE7: number
declare const MT_ROCKCRUMBLE8: number
declare const MT_ROCKCRUMBLE9: number
declare const MT_ROCKCRUMBLE10: number
declare const MT_ROCKCRUMBLE11: number
declare const MT_ROCKCRUMBLE12: number
declare const MT_ROCKCRUMBLE13: number
declare const MT_ROCKCRUMBLE14: number
declare const MT_ROCKCRUMBLE15: number
declare const MT_ROCKCRUMBLE16: number
declare const MT_GFZDEBRIS: number
declare const MT_BRICKDEBRIS: number
declare const MT_WOODDEBRIS: number
declare const MT_REDBRICKDEBRIS: number
declare const MT_BLUEBRICKDEBRIS: number
declare const MT_YELLOWBRICKDEBRIS: number
declare const MT_NAMECHECK: number
declare const MT_RAY: number