declare const TUTORL: number
declare const GFZ1: number
declare const GFZ2: number
declare const VSBOSS: number
declare const VSALT: number
declare const THZ1: number
declare const THZ2: number
declare const DSZ1: number
declare const DSZ2: number
declare const CEZ1: number
declare const CEZR: number
declare const CEZ2: number
declare const ACZ1: number
declare const ACZ2: number
declare const VSFANG: number
declare const RVZ1: number
declare const RVZ2: number
declare const RVZALT: number
declare const DCZ: number
declare const ERZ1: number
declare const ERZ2: number
declare const DISCO: number
declare const BCZ1: number
declare const VSMETL: number
declare const BCZ2: number
declare const VSBRAK: number

declare const FHZ: number
declare const MARIO1: number
declare const MARIO2: number
declare const THZALT: number
declare const HAUNTD: number
declare const AGZ: number
declare const ATZ: number
declare const CCZ: number
declare const DHZ: number
declare const APZ1: number
declare const APZ2: number

declare const SPEC1: number
declare const SPEC2: number
declare const SPEC3: number
declare const SPEC4: number
declare const SPEC5: number
declare const SPEC6: number
declare const SPEC7: number
declare const BHZ: number
declare const SPEC8: number
declare const OSPEC: number
declare const OSPEC2: number

declare const GFZALT: number
declare const AGZALT: number
declare const VSAGZ: number
declare const MP_WTR: number
declare const MP_ICE: number
declare const MP_RAI: number
declare const MP_AIR: number
declare const MP_SUN: number
declare const MP_DES: number
declare const MP_DOM: number
declare const MP_GHZ: number
declare const MP_MED: number
declare const MP_0RI: number
declare const MP_COA: number
declare const MP_FIR: number
declare const MP_FOR: number
declare const MP_FR2: number
declare const MP_GL2: number
declare const MP_GLZ: number
declare const MP_MIN: number
declare const MP_MRZ: number
declare const MP_WT2: number

declare const _STJR: number
declare const OINTRO: number
declare const _INTRO: number
declare const _ENDB: number
declare const _ENDG: number
declare const _CREDS: number
declare const _TITLE: number
declare const _CHSEL: number
declare const _RECAT: number
declare const _NITAT: number
declare const _INTER: number
declare const _INV: number
declare const _MINV: number
declare const _SHOES: number
declare const _1UP: number
declare const _SUPER: number
declare const _DROWN: number
declare const _NTIME: number
declare const _CLEAR: number
declare const _GOVER: number
declare const _CONTI: number