declare const PA_ETC: number
declare const PA_IDLE: number
declare const PA_EDGE: number
declare const PA_WALK: number
declare const PA_RUN: number
declare const PA_DASH: number
declare const PA_PAIN: number
declare const PA_ROLL: number
declare const PA_JUMP: number
declare const PA_SPRING: number
declare const PA_FALL: number
declare const PA_ABILITY: number
declare const PA_ABILITY2: number
declare const PA_RIDE: number