declare const PF_FLIPCAM: number
declare const PF_ANALOGMODE: number
declare const PF_DIRECTIONCHAR: number
declare const PF_AUTOBRAKE: number
declare const PF_GODMODE: number
declare const PF_NOCLIP: number
declare const PF_INVIS: number
declare const PF_ATTACKDOWN: number
declare const PF_SPINDOWN: number
declare const PF_JUMPDOWN: number
declare const PF_WPNDOWN: number
declare const PF_STASIS: number
declare const PF_JUMPSTASIS: number
declare const PF_FULLSTASIS: number
declare const PF_APPLYAUTOBRAKE: number
declare const PF_STARTJUMP: number
declare const PF_JUMPED: number
declare const PF_NOJUMPDAMAGE: number
declare const PF_SPINNING: number
declare const PF_STARTDASH: number
declare const PF_THOKKED: number
declare const PF_SHIELDABILITY: number
declare const PF_GLIDING: number
declare const PF_BOUNCING: number
declare const PF_SLIDING: number
declare const PF_TRANSFERTOCLOSEST: number
declare const PF_DRILLING: number
declare const PF_GAMETYPEOVER: number
declare const PF_TAGIT: number
declare const PF_FORCESTRAFE: number
declare const PF_CANCARRY: number
declare const PF_FINISHED: number