declare const POF_CLIPLINES: number
declare const POF_CLIPPLANES: number
declare const POF_SOLID: number
declare const POF_TESTHEIGHT: number
declare const POF_RENDERSIDES: number
declare const POF_RENDERTOP: number
declare const POF_RENDERBOTTOM: number
declare const POF_RENDERPLANES: number
declare const POF_RENDERALL: number
declare const POF_INVERT: number
declare const POF_INVERTPLANES: number
declare const POF_INVERTPLANESONLY: number
declare const POF_PUSHABLESTOP: number
declare const POF_LDEXEC: number
declare const POF_ONESIDE: number
declare const POF_NOSPECIALS: number
declare const POF_SPLAT: number