declare const pw_invulnerability: number
declare const pw_sneakers: number
declare const pw_flashing: number
declare const pw_shield: number
declare const pw_carry: number
declare const pw_tailsfly: number
declare const pw_underwater: number
declare const pw_spacetime: number
declare const pw_extralife: number
declare const pw_pushing: number
declare const pw_justsprung: number
declare const pw_noautobrake: number
declare const pw_super: number
declare const pw_gravityboots: number
declare const pw_infinityring: number
declare const pw_automaticring: number
declare const pw_bouncering: number
declare const pw_scatterring: number
declare const pw_grenadering: number
declare const pw_explosionring: number
declare const pw_railring: number
declare const pw_emeralds: number
declare const pw_nights_superloop: number
declare const pw_nights_helper: number
declare const pw_nights_linkfreeze: number
declare const pw_nocontrol: number
declare const pw_dye: number
declare const pw_justlaunched: number
declare const pw_ignorelatch: number