declare const RF_HORIZONTALFLIP: number
declare const RF_VERTICALFLIP: number
declare const RF_ABSOLUTEOFFSETS: number
declare const RF_FLIPOFFSETS: number
declare const RF_SPLATMASK: number
declare const RF_SLOPESPLAT: number
declare const RF_OBJECTSLOPESPLAT: number
declare const RF_NOSPLATBILLBOARD: number
declare const RF_NOSPLATROLLANGLE: number
declare const RF_BRIGHTMASK: number
declare const RF_FULLBRIGHT: number
declare const RF_FULLDARK: number
declare const RF_SEMIBRIGHT: number
declare const RF_NOCOLORMAPS: number
declare const RF_SPRITETYPEMASK: number
declare const RF_PAPERSPRITE: number
declare const RF_FLOORSPRITE: number
declare const RF_SHADOWDRAW: number
declare const RF_SHADOWEFFECTS: number
declare const RF_DROPSHADOW: number