declare const SF_TOTALLYSINGLE: number
declare const SF_NOMULTIPLESOUND: number
declare const SF_OUTSIDESOUND: number
declare const SF_X4AWAYSOUND: number
declare const SF_X8AWAYSOUND: number
declare const SF_NOINTERRUPT: number
declare const SF_X2AWAYSOUND: number
declare const SF_SUPER: number
declare const SF_NOSUPERSPIN: number
declare const SF_NOSPINDASHDUST: number
declare const SF_HIRES: number
declare const SF_NOSKID: number
declare const SF_NOSPEEDADJUST: number
declare const SF_RUNONWATER: number
declare const SF_NOJUMPSPIN: number
declare const SF_NOJUMPDAMAGE: number
declare const SF_STOMPDAMAGE: number
declare const SF_MARIODAMAGE: number
declare const SF_MACHINE: number
declare const SF_DASHMODE: number
declare const SF_FASTEDGE: number
declare const SF_MULTIABILITY: number
declare const SF_NONIGHTSROTATION: number
declare const SF_NONIGHTSSUPER: number
declare const SF_NOSUPERSPRITES: number
declare const SF_NOSUPERJUMPBOOST: number
declare const SF_CANBUSTWALLS: number
declare const SF_NOSHIELDABILITY: number