declare const sfx_None: number
declare const sfx_altdi1: number
declare const sfx_altdi2: number
declare const sfx_altdi3: number
declare const sfx_altdi4: number
declare const sfx_altow1: number
declare const sfx_altow2: number
declare const sfx_altow3: number
declare const sfx_altow4: number
declare const sfx_victr1: number
declare const sfx_victr2: number
declare const sfx_victr3: number
declare const sfx_victr4: number
declare const sfx_gasp: number
declare const sfx_jump: number
declare const sfx_pudpud: number
declare const sfx_putput: number
declare const sfx_spin: number
declare const sfx_spndsh: number
declare const sfx_thok: number
declare const sfx_zoom: number
declare const sfx_skid: number
declare const sfx_ambint: number
declare const sfx_alarm: number
declare const sfx_buzz1: number
declare const sfx_buzz2: number
declare const sfx_buzz3: number
declare const sfx_buzz4: number
declare const sfx_crumbl: number
declare const sfx_fire: number
declare const sfx_grind: number
declare const sfx_laser: number
declare const sfx_mswing: number
declare const sfx_pstart: number
declare const sfx_pstop: number
declare const sfx_steam1: number
declare const sfx_steam2: number
declare const sfx_wbreak: number
declare const sfx_ambmac: number
declare const sfx_spsmsh: number
declare const sfx_rainin: number
declare const sfx_litng1: number
declare const sfx_litng2: number
declare const sfx_litng3: number
declare const sfx_litng4: number
declare const sfx_athun1: number
declare const sfx_athun2: number
declare const sfx_amwtr1: number
declare const sfx_amwtr2: number
declare const sfx_amwtr3: number
declare const sfx_amwtr4: number
declare const sfx_amwtr5: number
declare const sfx_amwtr6: number
declare const sfx_amwtr7: number
declare const sfx_amwtr8: number
declare const sfx_bubbl1: number
declare const sfx_bubbl2: number
declare const sfx_bubbl3: number
declare const sfx_bubbl4: number
declare const sfx_bubbl5: number
declare const sfx_floush: number
declare const sfx_splash: number
declare const sfx_splish: number
declare const sfx_wdrip1: number
declare const sfx_wdrip2: number
declare const sfx_wdrip3: number
declare const sfx_wdrip4: number
declare const sfx_wdrip5: number
declare const sfx_wdrip6: number
declare const sfx_wdrip7: number
declare const sfx_wdrip8: number
declare const sfx_wslap: number
declare const sfx_doora1: number
declare const sfx_doorb1: number
declare const sfx_doorc1: number
declare const sfx_doorc2: number
declare const sfx_doord1: number
declare const sfx_doord2: number
declare const sfx_eleva1: number
declare const sfx_eleva2: number
declare const sfx_eleva3: number
declare const sfx_elevb1: number
declare const sfx_elevb2: number
declare const sfx_elevb3: number
declare const sfx_ambin2: number
declare const sfx_lavbub: number
declare const sfx_rocks1: number
declare const sfx_rocks2: number
declare const sfx_rocks3: number
declare const sfx_rocks4: number
declare const sfx_rumbam: number
declare const sfx_rumble: number
declare const sfx_appear: number
declare const sfx_bkpoof: number
declare const sfx_bnce1: number
declare const sfx_bnce2: number
declare const sfx_cannon: number
declare const sfx_cgot: number
declare const sfx_cybdth: number
declare const sfx_deton: number
declare const sfx_ding: number
declare const sfx_dmpain: number
declare const sfx_drown: number
declare const sfx_fizzle: number
declare const sfx_gbeep: number
declare const sfx_wepfir: number
declare const sfx_ghit: number
declare const sfx_gloop: number
declare const sfx_gspray: number
declare const sfx_gravch: number
declare const sfx_itemup: number
declare const sfx_jet: number
declare const sfx_jshard: number
declare const sfx_lose: number
declare const sfx_lvpass: number
declare const sfx_mindig: number
declare const sfx_mixup: number
declare const sfx_monton: number
declare const sfx_pogo: number
declare const sfx_pop: number
declare const sfx_rail1: number
declare const sfx_rail2: number
declare const sfx_rlaunc: number
declare const sfx_shield: number
declare const sfx_wirlsg: number
declare const sfx_forcsg: number
declare const sfx_frcssg: number
declare const sfx_elemsg: number
declare const sfx_armasg: number
declare const sfx_attrsg: number
declare const sfx_shldls: number
declare const sfx_spdpad: number
declare const sfx_spkdth: number
declare const sfx_spring: number
declare const sfx_statu1: number
declare const sfx_statu2: number
declare const sfx_strpst: number
declare const sfx_supert: number
declare const sfx_telept: number
declare const sfx_tink: number
declare const sfx_token: number
declare const sfx_trfire: number
declare const sfx_trpowr: number
declare const sfx_turhit: number
declare const sfx_wdjump: number
declare const sfx_shrpsp: number
declare const sfx_shrpgo: number
declare const sfx_mswarp: number
declare const sfx_mspogo: number
declare const sfx_boingf: number
declare const sfx_corkp: number
declare const sfx_corkh: number
declare const sfx_alart: number
declare const sfx_vwre: number
declare const sfx_bowl: number
declare const sfx_chuchu: number
declare const sfx_bsnipe: number
declare const sfx_sprong: number
declare const sfx_lvfal1: number
declare const sfx_pscree: number
declare const sfx_iceb: number
declare const sfx_shattr: number
declare const sfx_antiri: number
declare const sfx_chchng: number
declare const sfx_dwnind: number
declare const sfx_emfind: number
declare const sfx_flgcap: number
declare const sfx_menu1: number
declare const sfx_oneup: number
declare const sfx_ptally: number
declare const sfx_radio: number
declare const sfx_wepchg: number
declare const sfx_wtrdng: number
declare const sfx_zelda: number
declare const sfx_adderr: number
declare const sfx_notadd: number
declare const sfx_addfil: number
declare const sfx_ideya: number
declare const sfx_xideya: number
declare const sfx_nbmper: number
declare const sfx_nxbump: number
declare const sfx_ncchip: number
declare const sfx_ncitem: number
declare const sfx_nxitem: number
declare const sfx_ngdone: number
declare const sfx_nxdone: number
declare const sfx_drill1: number
declare const sfx_drill2: number
declare const sfx_ncspec: number
declare const sfx_nghurt: number
declare const sfx_ngskid: number
declare const sfx_hoop1: number
declare const sfx_hoop2: number
declare const sfx_hoop3: number
declare const sfx_hidden: number
declare const sfx_prloop: number
declare const sfx_timeup: number
declare const sfx_ngjump: number
declare const sfx_peww: number
declare const sfx_lntsit: number
declare const sfx_lntdie: number
declare const sfx_pumpkn: number
declare const sfx_ghosty: number
declare const sfx_koopfr: number
declare const sfx_mario1: number
declare const sfx_mario2: number
declare const sfx_mario3: number
declare const sfx_mario4: number
declare const sfx_mario5: number
declare const sfx_mario6: number
declare const sfx_mario7: number
declare const sfx_mario8: number
declare const sfx_mario9: number
declare const sfx_marioa: number
declare const sfx_thwomp: number
declare const sfx_bebomb: number
declare const sfx_bechrg: number
declare const sfx_becrsh: number
declare const sfx_bedeen: number
declare const sfx_bedie1: number
declare const sfx_bedie2: number
declare const sfx_beeyow: number
declare const sfx_befall: number
declare const sfx_befire: number
declare const sfx_beflap: number
declare const sfx_begoop: number
declare const sfx_begrnd: number
declare const sfx_behurt: number
declare const sfx_bejet1: number
declare const sfx_belnch: number
declare const sfx_beoutb: number
declare const sfx_beragh: number
declare const sfx_beshot: number
declare const sfx_bestep: number
declare const sfx_bestp2: number
declare const sfx_bewar1: number
declare const sfx_bewar2: number
declare const sfx_bewar3: number
declare const sfx_bewar4: number
declare const sfx_bexpld: number
declare const sfx_bgxpld: number
declare const sfx_beelec: number
declare const sfx_brakrl: number
declare const sfx_brakrx: number
declare const sfx_s1a0: number
declare const sfx_s1a1: number
declare const sfx_s1a2: number
declare const sfx_s1a3: number
declare const sfx_s1a4: number
declare const sfx_s1a5: number
declare const sfx_s1a6: number
declare const sfx_s1a7: number
declare const sfx_s1a8: number
declare const sfx_s1a9: number
declare const sfx_s1aa: number
declare const sfx_s1ab: number
declare const sfx_s1ac: number
declare const sfx_s1ad: number
declare const sfx_s1ae: number
declare const sfx_s1af: number
declare const sfx_s1b0: number
declare const sfx_s1b1: number
declare const sfx_s1b2: number
declare const sfx_s1b3: number
declare const sfx_s1b4: number
declare const sfx_s1b5: number
declare const sfx_s1b6: number
declare const sfx_s1b7: number
declare const sfx_s1b8: number
declare const sfx_s1b9: number
declare const sfx_s1ba: number
declare const sfx_s1bb: number
declare const sfx_s1bc: number
declare const sfx_s1bd: number
declare const sfx_s1be: number
declare const sfx_s1bf: number
declare const sfx_s1c0: number
declare const sfx_s1c1: number
declare const sfx_s1c2: number
declare const sfx_s1c3: number
declare const sfx_s1c4: number
declare const sfx_s1c5: number
declare const sfx_s1c6: number
declare const sfx_s1c7: number
declare const sfx_s1c8: number
declare const sfx_s1c9: number
declare const sfx_s1ca: number
declare const sfx_s1cb: number
declare const sfx_s1cc: number
declare const sfx_s1cd: number
declare const sfx_s1ce: number
declare const sfx_s1cf: number
declare const sfx_s220: number
declare const sfx_s221: number
declare const sfx_s222: number
declare const sfx_s223: number
declare const sfx_s224: number
declare const sfx_s225: number
declare const sfx_s226: number
declare const sfx_s227: number
declare const sfx_s228: number
declare const sfx_s229: number
declare const sfx_s22a: number
declare const sfx_s22b: number
declare const sfx_s22c: number
declare const sfx_s22d: number
declare const sfx_s22e: number
declare const sfx_s22f: number
declare const sfx_s230: number
declare const sfx_s231: number
declare const sfx_s232: number
declare const sfx_s233: number
declare const sfx_s234: number
declare const sfx_s235: number
declare const sfx_s236: number
declare const sfx_s237: number
declare const sfx_s238: number
declare const sfx_s239: number
declare const sfx_s23a: number
declare const sfx_s23b: number
declare const sfx_s23c: number
declare const sfx_s23d: number
declare const sfx_s23e: number
declare const sfx_s23f: number
declare const sfx_s240: number
declare const sfx_s241: number
declare const sfx_s242: number
declare const sfx_s243: number
declare const sfx_s244: number
declare const sfx_s245: number
declare const sfx_s246: number
declare const sfx_s247: number
declare const sfx_s248: number
declare const sfx_s249: number
declare const sfx_s24a: number
declare const sfx_s24b: number
declare const sfx_s24c: number
declare const sfx_s24d: number
declare const sfx_s24e: number
declare const sfx_s24f: number
declare const sfx_s250: number
declare const sfx_s251: number
declare const sfx_s252: number
declare const sfx_s253: number
declare const sfx_s254: number
declare const sfx_s255: number
declare const sfx_s256: number
declare const sfx_s257: number
declare const sfx_s258: number
declare const sfx_s259: number
declare const sfx_s25a: number
declare const sfx_s25b: number
declare const sfx_s25c: number
declare const sfx_s25d: number
declare const sfx_s25e: number
declare const sfx_s25f: number
declare const sfx_s260: number
declare const sfx_s3k2b: number
declare const sfx_s3k33: number
declare const sfx_s3k34: number
declare const sfx_s3k35: number
declare const sfx_s3k36: number
declare const sfx_s3k37: number
declare const sfx_s3k38: number
declare const sfx_s3k39: number
declare const sfx_s3k3a: number
declare const sfx_s3k3b: number
declare const sfx_s3k3c: number
declare const sfx_s3k3d: number
declare const sfx_s3k3e: number
declare const sfx_s3k3f: number
declare const sfx_s3k40: number
declare const sfx_s3k41: number
declare const sfx_s3k42: number
declare const sfx_s3k43: number
declare const sfx_s3k44: number
declare const sfx_s3k45: number
declare const sfx_s3k46: number
declare const sfx_s3k47: number
declare const sfx_s3k48: number
declare const sfx_s3k49: number
declare const sfx_s3k4a: number
declare const sfx_s3k4b: number
declare const sfx_s3k4c: number
declare const sfx_s3k4d: number
declare const sfx_s3k4e: number
declare const sfx_s3k4f: number
declare const sfx_s3k50: number
declare const sfx_s3k51: number
declare const sfx_s3k52: number
declare const sfx_s3k53: number
declare const sfx_s3k54: number
declare const sfx_s3k55: number
declare const sfx_s3k56: number
declare const sfx_s3k57: number
declare const sfx_s3k58: number
declare const sfx_s3k59: number
declare const sfx_s3k5a: number
declare const sfx_s3k5b: number
declare const sfx_s3k5c: number
declare const sfx_s3k5d: number
declare const sfx_s3k5e: number
declare const sfx_s3k5f: number
declare const sfx_s3k60: number
declare const sfx_s3k61: number
declare const sfx_s3k62: number
declare const sfx_s3k63: number
declare const sfx_s3k64: number
declare const sfx_s3k65: number
declare const sfx_s3k66: number
declare const sfx_s3k67: number
declare const sfx_s3k68: number
declare const sfx_s3k69: number
declare const sfx_s3k6a: number
declare const sfx_s3k6b: number
declare const sfx_s3k6c: number
declare const sfx_s3k6d: number
declare const sfx_s3k6e: number
declare const sfx_s3k6f: number
declare const sfx_s3k70: number
declare const sfx_s3k71: number
declare const sfx_s3k72: number
declare const sfx_s3k73: number
declare const sfx_s3k74: number
declare const sfx_s3k75: number
declare const sfx_s3k76: number
declare const sfx_s3k77: number
declare const sfx_s3k78: number
declare const sfx_s3k79: number
declare const sfx_s3k7a: number
declare const sfx_s3k7b: number
declare const sfx_s3k7c: number
declare const sfx_s3k7d: number
declare const sfx_s3k7e: number
declare const sfx_s3k7f: number
declare const sfx_s3k80: number
declare const sfx_s3k81: number
declare const sfx_s3k82: number
declare const sfx_s3k83: number
declare const sfx_s3k84: number
declare const sfx_s3k85: number
declare const sfx_s3k86: number
declare const sfx_s3k87: number
declare const sfx_s3k88: number
declare const sfx_s3k89: number
declare const sfx_s3k8a: number
declare const sfx_s3k8b: number
declare const sfx_s3k8c: number
declare const sfx_s3k8d: number
declare const sfx_s3k8e: number
declare const sfx_s3k8f: number
declare const sfx_s3k90: number
declare const sfx_s3k91: number
declare const sfx_s3k92: number
declare const sfx_s3k93: number
declare const sfx_s3k94: number
declare const sfx_s3k95: number
declare const sfx_s3k96: number
declare const sfx_s3k97: number
declare const sfx_s3k98: number
declare const sfx_s3k99: number
declare const sfx_s3k9a: number
declare const sfx_s3k9b: number
declare const sfx_s3k9c: number
declare const sfx_s3k9d: number
declare const sfx_s3k9e: number
declare const sfx_s3k9f: number
declare const sfx_s3ka0: number
declare const sfx_s3ka1: number
declare const sfx_s3ka2: number
declare const sfx_s3ka3: number
declare const sfx_s3ka4: number
declare const sfx_s3ka5: number
declare const sfx_s3ka6: number
declare const sfx_s3ka7: number
declare const sfx_s3ka8: number
declare const sfx_s3ka9: number
declare const sfx_s3kaa: number
declare const sfx_s3kab: number
declare const sfx_s3kab1: number
declare const sfx_s3kab2: number
declare const sfx_s3kab3: number
declare const sfx_s3kab4: number
declare const sfx_s3kab5: number
declare const sfx_s3kab6: number
declare const sfx_s3kab7: number
declare const sfx_s3kab8: number
declare const sfx_s3kab9: number
declare const sfx_s3kaba: number
declare const sfx_s3kabb: number
declare const sfx_s3kabc: number
declare const sfx_s3kabd: number
declare const sfx_s3kabe: number
declare const sfx_s3kabf: number
declare const sfx_s3kac: number
declare const sfx_s3kad: number
declare const sfx_s3kae: number
declare const sfx_s3kaf: number
declare const sfx_s3kb0: number
declare const sfx_s3kb1: number
declare const sfx_s3kb2: number
declare const sfx_s3kb3: number
declare const sfx_s3kb4: number
declare const sfx_s3kb5: number
declare const sfx_s3kb6: number
declare const sfx_s3kb7: number
declare const sfx_s3kb8: number
declare const sfx_s3kb9: number
declare const sfx_s3kba: number
declare const sfx_s3kbb: number
declare const sfx_s3kbcs: number
declare const sfx_s3kbcl: number
declare const sfx_s3kbds: number
declare const sfx_s3kbdl: number
declare const sfx_s3kbes: number
declare const sfx_s3kbel: number
declare const sfx_s3kbfs: number
declare const sfx_s3kbfl: number
declare const sfx_s3kc0s: number
declare const sfx_s3kc0l: number
declare const sfx_s3kc1s: number
declare const sfx_s3kc1l: number
declare const sfx_s3kc2s: number
declare const sfx_s3kc2l: number
declare const sfx_s3kc3s: number
declare const sfx_s3kc3l: number
declare const sfx_s3kc4s: number
declare const sfx_s3kc4l: number
declare const sfx_s3kc5s: number
declare const sfx_s3kc5l: number
declare const sfx_s3kc6s: number
declare const sfx_s3kc6l: number
declare const sfx_s3kc7s: number
declare const sfx_s3kc7l: number
declare const sfx_s3kc8s: number
declare const sfx_s3kc8l: number
declare const sfx_s3kc9s: number
declare const sfx_s3kc9l: number
declare const sfx_s3kcas: number
declare const sfx_s3kcal: number
declare const sfx_s3kcbs: number
declare const sfx_s3kcbl: number
declare const sfx_s3kccs: number
declare const sfx_s3kccl: number
declare const sfx_s3kcds: number
declare const sfx_s3kcdl: number
declare const sfx_s3kces: number
declare const sfx_s3kcel: number
declare const sfx_s3kcfs: number
declare const sfx_s3kcfl: number
declare const sfx_s3kd0s: number
declare const sfx_s3kd0l: number
declare const sfx_s3kd1s: number
declare const sfx_s3kd1l: number
declare const sfx_s3kd2s: number
declare const sfx_s3kd2l: number
declare const sfx_s3kd3s: number
declare const sfx_s3kd3l: number
declare const sfx_s3kd4s: number
declare const sfx_s3kd4l: number
declare const sfx_s3kd5s: number
declare const sfx_s3kd5l: number
declare const sfx_s3kd6s: number
declare const sfx_s3kd6l: number
declare const sfx_s3kd7s: number
declare const sfx_s3kd7l: number
declare const sfx_s3kd8s: number
declare const sfx_s3kd8l: number
declare const sfx_s3kd9s: number
declare const sfx_s3kd9l: number
declare const sfx_s3kdas: number
declare const sfx_s3kdal: number
declare const sfx_s3kdbs: number
declare const sfx_s3kdbl: number
declare const sfx_3db06: number
declare const sfx_3db09: number
declare const sfx_3db14: number
declare const sfx_3db16: number
declare const sfx_cdfm00: number
declare const sfx_cdfm01: number
declare const sfx_cdfm02: number
declare const sfx_cdfm03: number
declare const sfx_cdfm04: number
declare const sfx_cdfm05: number
declare const sfx_cdfm06: number
declare const sfx_cdfm07: number
declare const sfx_cdfm08: number
declare const sfx_cdfm09: number
declare const sfx_cdfm10: number
declare const sfx_cdfm11: number
declare const sfx_cdfm12: number
declare const sfx_cdfm13: number
declare const sfx_cdfm14: number
declare const sfx_cdfm15: number
declare const sfx_cdfm16: number
declare const sfx_cdfm17: number
declare const sfx_cdfm18: number
declare const sfx_cdfm19: number
declare const sfx_cdfm20: number
declare const sfx_cdfm21: number
declare const sfx_cdfm22: number
declare const sfx_cdfm23: number
declare const sfx_cdfm24: number
declare const sfx_cdfm25: number
declare const sfx_cdfm26: number
declare const sfx_cdfm27: number
declare const sfx_cdfm28: number
declare const sfx_cdfm29: number
declare const sfx_cdfm30: number
declare const sfx_cdfm31: number
declare const sfx_cdfm32: number
declare const sfx_cdfm33: number
declare const sfx_cdfm34: number
declare const sfx_cdfm35: number
declare const sfx_cdfm36: number
declare const sfx_cdfm37: number
declare const sfx_cdfm38: number
declare const sfx_cdfm39: number
declare const sfx_cdfm40: number
declare const sfx_cdfm41: number
declare const sfx_cdfm42: number
declare const sfx_cdfm43: number
declare const sfx_cdfm44: number
declare const sfx_cdfm45: number
declare const sfx_cdfm46: number
declare const sfx_cdfm47: number
declare const sfx_cdfm48: number
declare const sfx_cdfm49: number
declare const sfx_cdfm50: number
declare const sfx_cdfm51: number
declare const sfx_cdfm52: number
declare const sfx_cdfm53: number
declare const sfx_cdfm54: number
declare const sfx_cdfm55: number
declare const sfx_cdfm56: number
declare const sfx_cdfm57: number
declare const sfx_cdfm58: number
declare const sfx_cdfm59: number
declare const sfx_cdfm60: number
declare const sfx_cdfm61: number
declare const sfx_cdfm62: number
declare const sfx_cdfm63: number
declare const sfx_cdfm64: number
declare const sfx_cdfm65: number
declare const sfx_cdfm66: number
declare const sfx_cdfm67: number
declare const sfx_cdfm68: number
declare const sfx_cdfm69: number
declare const sfx_cdfm70: number
declare const sfx_cdfm71: number
declare const sfx_cdfm72: number
declare const sfx_cdfm73: number
declare const sfx_cdfm74: number
declare const sfx_cdfm75: number
declare const sfx_cdfm76: number
declare const sfx_cdfm77: number
declare const sfx_cdfm78: number
declare const sfx_cdfm79: number
declare const sfx_cdpcm0: number
declare const sfx_cdpcm1: number
declare const sfx_cdpcm2: number
declare const sfx_cdpcm3: number
declare const sfx_cdpcm4: number
declare const sfx_cdpcm5: number
declare const sfx_cdpcm6: number
declare const sfx_cdpcm7: number
declare const sfx_cdpcm8: number
declare const sfx_cdpcm9: number
declare const sfx_kc2a: number
declare const sfx_kc2b: number
declare const sfx_kc2c: number
declare const sfx_kc2d: number
declare const sfx_kc2e: number
declare const sfx_kc2f: number
declare const sfx_kc30: number
declare const sfx_kc31: number
declare const sfx_kc32: number
declare const sfx_kc33: number
declare const sfx_kc34: number
declare const sfx_kc35: number
declare const sfx_kc36: number
declare const sfx_kc37: number
declare const sfx_kc38: number
declare const sfx_kc39: number
declare const sfx_kc3a: number
declare const sfx_kc3b: number
declare const sfx_kc3c: number
declare const sfx_kc3d: number
declare const sfx_kc3e: number
declare const sfx_kc3f: number
declare const sfx_kc40: number
declare const sfx_kc41: number
declare const sfx_kc42: number
declare const sfx_kc43: number
declare const sfx_kc44: number
declare const sfx_kc45: number
declare const sfx_kc46: number
declare const sfx_kc47: number
declare const sfx_kc48: number
declare const sfx_kc49: number
declare const sfx_kc4a: number
declare const sfx_kc4b: number
declare const sfx_kc4c: number
declare const sfx_kc4d: number
declare const sfx_kc4e: number
declare const sfx_kc4f: number
declare const sfx_kc50: number
declare const sfx_kc51: number
declare const sfx_kc52: number
declare const sfx_kc53: number
declare const sfx_kc54: number
declare const sfx_kc55: number
declare const sfx_kc56: number
declare const sfx_kc57: number
declare const sfx_kc58: number
declare const sfx_kc59: number
declare const sfx_kc5a: number
declare const sfx_kc5b: number
declare const sfx_kc5c: number
declare const sfx_kc5d: number
declare const sfx_kc5e: number
declare const sfx_kc5f: number
declare const sfx_kc60: number
declare const sfx_kc61: number
declare const sfx_kc62: number
declare const sfx_kc63: number
declare const sfx_kc64: number
declare const sfx_kc65: number
declare const sfx_kc66: number
declare const sfx_kc67: number
declare const sfx_kc68: number
declare const sfx_kc69: number
declare const sfx_kc6b: number
declare const sfx_kc6c: number
declare const sfx_kc6d: number
declare const sfx_kc6e: number
