declare const SH_NONE: number
declare const SH_PITY: number
declare const SH_WHIRLWIND: number
declare const SH_ARMAGEDDON: number
declare const SH_PINK: number
declare const SH_ELEMENTAL: number
declare const SH_ATTRACT: number
declare const SH_FLAMEAURA: number
declare const SH_BUBBLEWRAP: number
declare const SH_THUNDERCOIN: number
declare const SH_FORCE: number
declare const SH_FORCEHP: number
declare const SH_FIREFLOWER: number
declare const SH_STACK: number
declare const SH_NOSTACK: number
declare const SH_PROTECTFIRE: number
declare const SH_PROTECTWATER: number
declare const SH_PROTECTELECTRIC: number
declare const SH_PROTECTSPIKE: number
