declare const SKINCOLOR_WHITE: number
declare const SKINCOLOR_BONE: number
declare const SKINCOLOR_CLOUDY: number
declare const SKINCOLOR_GREY: number
declare const SKINCOLOR_SILVER: number
declare const SKINCOLOR_CARBON: number
declare const SKINCOLOR_JET: number
declare const SKINCOLOR_BLACK: number
declare const SKINCOLOR_AETHER: number
declare const SKINCOLOR_SLATE: number
declare const SKINCOLOR_BLUEBELL: number
declare const SKINCOLOR_PINK: number
declare const SKINCOLOR_YOGURT: number
declare const SKINCOLOR_BROWN: number
declare const SKINCOLOR_BRONZE: number
declare const SKINCOLOR_TAN: number
declare const SKINCOLOR_BEIGE: number
declare const SKINCOLOR_MOSS: number
declare const SKINCOLOR_AZURE: number
declare const SKINCOLOR_LAVENDER: number
declare const SKINCOLOR_RUBY: number
declare const SKINCOLOR_SALMON: number
declare const SKINCOLOR_RED: number
declare const SKINCOLOR_CRIMSON: number
declare const SKINCOLOR_FLAME: number
declare const SKINCOLOR_KETCHUP: number
declare const SKINCOLOR_PEACHY: number
declare const SKINCOLOR_QUAIL: number
declare const SKINCOLOR_SUNSET: number
declare const SKINCOLOR_COPPER: number
declare const SKINCOLOR_APRICOT: number
declare const SKINCOLOR_ORANGE: number
declare const SKINCOLOR_RUST: number
declare const SKINCOLOR_GOLD: number
declare const SKINCOLOR_SANDY: number
declare const SKINCOLOR_YELLOW: number
declare const SKINCOLOR_OLIVE: number
declare const SKINCOLOR_LIME: number
declare const SKINCOLOR_PERIDOT: number
declare const SKINCOLOR_APPLE: number
declare const SKINCOLOR_GREEN: number
declare const SKINCOLOR_FOREST: number
declare const SKINCOLOR_EMERALD: number
declare const SKINCOLOR_MINT: number
declare const SKINCOLOR_SEAFOAM: number
declare const SKINCOLOR_AQUA: number
declare const SKINCOLOR_TEAL: number
declare const SKINCOLOR_WAVE: number
declare const SKINCOLOR_CYAN: number
declare const SKINCOLOR_SKY: number
declare const SKINCOLOR_CERULEAN: number
declare const SKINCOLOR_ICY: number
declare const SKINCOLOR_SAPPHIRE: number
declare const SKINCOLOR_CORNFLOWER: number
declare const SKINCOLOR_BLUE: number
declare const SKINCOLOR_COBALT: number
declare const SKINCOLOR_VAPOR: number
declare const SKINCOLOR_DUSK: number
declare const SKINCOLOR_PASTEL: number
declare const SKINCOLOR_PURPLE: number
declare const SKINCOLOR_BUBBLEGUM: number
declare const SKINCOLOR_MAGENTA: number
declare const SKINCOLOR_NEON: number
declare const SKINCOLOR_VIOLET: number
declare const SKINCOLOR_LILAC: number
declare const SKINCOLOR_PLUM: number
declare const SKINCOLOR_RASPBERRY: number
declare const SKINCOLOR_ROSY: number
declare const MAXSKINCOLORS: number
declare const SKINCOLOR_SUPERSILVER: number
declare const SKINCOLOR_SUPERSILVER2: number
declare const SKINCOLOR_SUPERSILVER3: number
declare const SKINCOLOR_SUPERSILVER4: number
declare const SKINCOLOR_SUPERSILVER5: number

declare const SKINCOLOR_SUPERRED1: number
declare const SKINCOLOR_SUPERRED2: number
declare const SKINCOLOR_SUPERRED3: number
declare const SKINCOLOR_SUPERRED4: number
declare const SKINCOLOR_SUPERRED5: number

declare const SKINCOLOR_SUPERORANGE1: number
declare const SKINCOLOR_SUPERORANGE2: number
declare const SKINCOLOR_SUPERORANGE3: number
declare const SKINCOLOR_SUPERORANGE4: number
declare const SKINCOLOR_SUPERORANGE5: number

declare const SKINCOLOR_SUPERGOLD1: number
declare const SKINCOLOR_SUPERGOLD2: number
declare const SKINCOLOR_SUPERGOLD3: number
declare const SKINCOLOR_SUPERGOLD4: number
declare const SKINCOLOR_SUPERGOLD5: number

declare const SKINCOLOR_SUPERPERIDOT1: number
declare const SKINCOLOR_SUPERPERIDOT2: number
declare const SKINCOLOR_SUPERPERIDOT3: number
declare const SKINCOLOR_SUPERPERIDOT4: number
declare const SKINCOLOR_SUPERPERIDOT5: number

declare const SKINCOLOR_SUPERSKY1: number
declare const SKINCOLOR_SUPERSKY2: number
declare const SKINCOLOR_SUPERSKY3: number
declare const SKINCOLOR_SUPERSKY4: number
declare const SKINCOLOR_SUPERSKY5: number

declare const SKINCOLOR_SUPERPURPLE1: number
declare const SKINCOLOR_SUPERPURPLE2: number
declare const SKINCOLOR_SUPERPURPLE3: number
declare const SKINCOLOR_SUPERPURPLE4: number
declare const SKINCOLOR_SUPERPURPLE5: number

declare const SKINCOLOR_SUPERRUST1: number
declare const SKINCOLOR_SUPERRUST2: number
declare const SKINCOLOR_SUPERRUST3: number
declare const SKINCOLOR_SUPERRUST4: number
declare const SKINCOLOR_SUPERRUST5: number

declare const SKINCOLOR_SUPERTAN1: number
declare const SKINCOLOR_SUPERTAN2: number
declare const SKINCOLOR_SUPERTAN3: number
declare const SKINCOLOR_SUPERTAN4: number
declare const SKINCOLOR_SUPERTAN5: number