declare const SKSSPIN: number
declare const SKSPUTPUT: number
declare const SKSPUDPUD: number
declare const SKSPLPAN1: number
declare const SKSPLPAN2: number
declare const SKSPLPAN3: number
declare const SKSPLPAN4: number
declare const SKSPLDET1: number
declare const SKSPLDET2: number
declare const SKSPLDET3: number
declare const SKSPLDET4: number
declare const SKSPLVCT1: number
declare const SKSPLVCT2: number
declare const SKSPLVCT3: number
declare const SKSPLVCT4: number
declare const SKSTHOK: number
declare const SKSSPNDSH: number
declare const SKSZOOM: number
declare const SKSSKID: number
declare const SKSGASP: number
declare const SKSJUMP: number