declare const SPR_NULL: number
declare const SPR_UNKN: number
declare const SPR_THOK: number
declare const SPR_PLAY: number
declare const SPR_POSS: number
declare const SPR_SPOS: number
declare const SPR_FISH: number
declare const SPR_BUZZ: number
declare const SPR_RBUZ: number
declare const SPR_JETB: number
declare const SPR_JETG: number
declare const SPR_CCOM: number
declare const SPR_DETN: number
declare const SPR_SKIM: number
declare const SPR_TRET: number
declare const SPR_TURR: number
declare const SPR_SHRP: number
declare const SPR_CRAB: number
declare const SPR_CR2B: number
declare const SPR_CSPR: number
declare const SPR_JJAW: number
declare const SPR_SNLR: number
declare const SPR_VLTR: number
declare const SPR_PNTY: number
declare const SPR_ARCH: number
declare const SPR_CBFS: number
declare const SPR_STAB: number
declare const SPR_SPSH: number
declare const SPR_ESHI: number
declare const SPR_GSNP: number
declare const SPR_GSNL: number
declare const SPR_GSNH: number
declare const SPR_MNUS: number
declare const SPR_MNUD: number
declare const SPR_SSHL: number
declare const SPR_UNID: number
declare const SPR_CANA: number
declare const SPR_CANG: number
declare const SPR_PYRE: number
declare const SPR_PTER: number
declare const SPR_DRAB: number
declare const SPR_JETF: number
declare const SPR_EGGM: number
declare const SPR_EGLZ: number
declare const SPR_EGGN: number
declare const SPR_TANK: number
declare const SPR_GOOP: number
declare const SPR_EGGO: number
declare const SPR_SEBH: number
declare const SPR_FAKE: number
declare const SPR_SHCK: number
declare const SPR_EGGP: number
declare const SPR_EFIR: number
declare const SPR_EGR1: number
declare const SPR_FANG: number
declare const SPR_BRKN: number
declare const SPR_WHAT: number
declare const SPR_VWRE: number
declare const SPR_PROJ: number
declare const SPR_FBOM: number
declare const SPR_FSGN: number
declare const SPR_BARX: number
declare const SPR_BARD: number
declare const SPR_EGGR: number
declare const SPR_BRAK: number
declare const SPR_BGOO: number
declare const SPR_BMSL: number
declare const SPR_EGGT: number
declare const SPR_RCKT: number
declare const SPR_ELEC: number
declare const SPR_TARG: number
declare const SPR_NPLM: number
declare const SPR_MNPL: number
declare const SPR_METL: number
declare const SPR_MSCF: number
declare const SPR_MSCB: number
declare const SPR_RING: number
declare const SPR_TRNG: number
declare const SPR_TOKE: number
declare const SPR_RFLG: number
declare const SPR_BFLG: number
declare const SPR_SPHR: number
declare const SPR_NCHP: number
declare const SPR_NSTR: number
declare const SPR_EMBM: number
declare const SPR_CEMG: number
declare const SPR_SHRD: number
declare const SPR_BBLS: number
declare const SPR_SIGN: number
declare const SPR_SPIK: number
declare const SPR_SFLM: number
declare const SPR_USPK: number
declare const SPR_WSPK: number
declare const SPR_WSPB: number
declare const SPR_STPT: number
declare const SPR_BMNE: number
declare const SPR_PUMI: number
declare const SPR_MSTV: number
declare const SPR_XLTV: number
declare const SPR_TRRI: number
declare const SPR_TBRI: number
declare const SPR_TVRI: number
declare const SPR_TVPI: number
declare const SPR_TVAT: number
declare const SPR_TVFO: number
declare const SPR_TVAR: number
declare const SPR_TVWW: number
declare const SPR_TVEL: number
declare const SPR_TVSS: number
declare const SPR_TVIV: number
declare const SPR_TV1U: number
declare const SPR_TV1P: number
declare const SPR_TVEG: number
declare const SPR_TVMX: number
declare const SPR_TVMY: number
declare const SPR_TVGV: number
declare const SPR_TVRC: number
declare const SPR_TV1K: number
declare const SPR_TVTK: number
declare const SPR_TVFL: number
declare const SPR_TVBB: number
declare const SPR_TVZP: number
declare const SPR_MISL: number
declare const SPR_TORP: number
declare const SPR_ENRG: number
declare const SPR_MINE: number
declare const SPR_JBUL: number
declare const SPR_TRLS: number
declare const SPR_CBLL: number
declare const SPR_AROW: number
declare const SPR_CFIR: number
declare const SPR_LETR: number
declare const SPR_FWR1: number
declare const SPR_FWR2: number
declare const SPR_FWR3: number
declare const SPR_FWR4: number
declare const SPR_BUS1: number
declare const SPR_BUS2: number
declare const SPR_BUS3: number
declare const SPR_TRE1: number
declare const SPR_TRE2: number
declare const SPR_TRE3: number
declare const SPR_TRE4: number
declare const SPR_TRE5: number
declare const SPR_TRE6: number
declare const SPR_THZP: number
declare const SPR_FWR5: number
declare const SPR_FWR6: number
declare const SPR_THZT: number
declare const SPR_ALRM: number
declare const SPR_GARG: number
declare const SPR_SEWE: number
declare const SPR_DRIP: number
declare const SPR_CORL: number
declare const SPR_BCRY: number
declare const SPR_KELP: number
declare const SPR_ALGA: number
declare const SPR_ALGB: number
declare const SPR_DSTG: number
declare const SPR_LIBE: number
declare const SPR_CHAN: number
declare const SPR_FLAM: number
declare const SPR_ESTA: number
declare const SPR_SMCH: number
declare const SPR_BMCH: number
declare const SPR_SMCE: number
declare const SPR_BMCE: number
declare const SPR_YSPB: number
declare const SPR_RSPB: number
declare const SPR_SFBR: number
declare const SPR_BFBR: number
declare const SPR_BANR: number
declare const SPR_PINE: number
declare const SPR_CEZB: number
declare const SPR_CNDL: number
declare const SPR_FLMH: number
declare const SPR_CTRC: number
declare const SPR_CFLG: number
declare const SPR_CSTA: number
declare const SPR_CBBS: number
declare const SPR_CABR: number
declare const SPR_BTBL: number
declare const SPR_STBL: number
declare const SPR_CACT: number
declare const SPR_WWSG: number
declare const SPR_WWS2: number
declare const SPR_WWS3: number
declare const SPR_OILL: number
declare const SPR_OILF: number
declare const SPR_BARR: number
declare const SPR_REMT: number
declare const SPR_TAZD: number
declare const SPR_ADST: number
declare const SPR_MCRT: number
declare const SPR_MCSP: number
declare const SPR_SALD: number
declare const SPR_TRAE: number
declare const SPR_TRAI: number
declare const SPR_STEA: number
declare const SPR_FLME: number
declare const SPR_DFLM: number
declare const SPR_LFAL: number
declare const SPR_JPLA: number
declare const SPR_TFLO: number
declare const SPR_WVIN: number
declare const SPR_XMS1: number
declare const SPR_XMS2: number
declare const SPR_XMS3: number
declare const SPR_XMS4: number
declare const SPR_XMS5: number
declare const SPR_XMS6: number
declare const SPR_FHZI: number
declare const SPR_ROSY: number
declare const SPR_PUMK: number
declare const SPR_HHPL: number
declare const SPR_SHRM: number
declare const SPR_HHZM: number
declare const SPR_BGAR: number
declare const SPR_RCRY: number
declare const SPR_CFLM: number
declare const SPR_BSZ1: number
declare const SPR_BSZ2: number
declare const SPR_BSZ3: number
declare const SPR_BST1: number
declare const SPR_BST2: number
declare const SPR_BST3: number
declare const SPR_BST4: number
declare const SPR_BST5: number
declare const SPR_BST6: number
declare const SPR_BSZ5: number
declare const SPR_BSZ6: number
declare const SPR_BSZ7: number
declare const SPR_BSZ8: number
declare const SPR_STLG: number
declare const SPR_DBAL: number
declare const SPR_ARMA: number
declare const SPR_ARMF: number
declare const SPR_ARMB: number
declare const SPR_WIND: number
declare const SPR_MAGN: number
declare const SPR_ELEM: number
declare const SPR_FORC: number
declare const SPR_PITY: number
declare const SPR_FIRS: number
declare const SPR_BUBS: number
declare const SPR_ZAPS: number
declare const SPR_IVSP: number
declare const SPR_SSPK: number
declare const SPR_GOAL: number
declare const SPR_FBUB: number
declare const SPR_FL01: number
declare const SPR_FL02: number
declare const SPR_FL03: number
declare const SPR_FL04: number
declare const SPR_FL05: number
declare const SPR_FL06: number
declare const SPR_FL07: number
declare const SPR_FL08: number
declare const SPR_FL09: number
declare const SPR_FL10: number
declare const SPR_FL11: number
declare const SPR_FL12: number
declare const SPR_FL13: number
declare const SPR_FL14: number
declare const SPR_FL15: number
declare const SPR_FL16: number
declare const SPR_FS01: number
declare const SPR_FS02: number
declare const SPR_FANS: number
declare const SPR_STEM: number
declare const SPR_BUMP: number
declare const SPR_BLON: number
declare const SPR_SPRY: number
declare const SPR_SPRR: number
declare const SPR_SPRB: number
declare const SPR_YSPR: number
declare const SPR_RSPR: number
declare const SPR_BSPR: number
declare const SPR_SSWY: number
declare const SPR_SSWR: number
declare const SPR_SSWB: number
declare const SPR_BSTY: number
declare const SPR_BSTR: number
declare const SPR_RAIN: number
declare const SPR_SNO1: number
declare const SPR_SPLH: number
declare const SPR_LSPL: number
declare const SPR_SPLA: number
declare const SPR_SMOK: number
declare const SPR_BUBL: number
declare const SPR_WZAP: number
declare const SPR_DUST: number
declare const SPR_FPRT: number
declare const SPR_TFOG: number
declare const SPR_SEED: number
declare const SPR_PRTL: number
declare const SPR_SCOR: number
declare const SPR_DRWN: number
declare const SPR_FLII: number
declare const SPR_LCKN: number
declare const SPR_TTAG: number
declare const SPR_GFLG: number
declare const SPR_FNSF: number
declare const SPR_CORK: number
declare const SPR_LHRT: number
declare const SPR_RRNG: number
declare const SPR_RNGB: number
declare const SPR_RNGR: number
declare const SPR_RNGI: number
declare const SPR_RNGA: number
declare const SPR_RNGE: number
declare const SPR_RNGS: number
declare const SPR_RNGG: number
declare const SPR_PIKB: number
declare const SPR_PIKR: number
declare const SPR_PIKA: number
declare const SPR_PIKE: number
declare const SPR_PIKS: number
declare const SPR_PIKG: number
declare const SPR_TAUT: number
declare const SPR_TGRE: number
declare const SPR_TSCR: number
declare const SPR_COIN: number
declare const SPR_CPRK: number
declare const SPR_GOOM: number
declare const SPR_BGOM: number
declare const SPR_FFWR: number
declare const SPR_FBLL: number
declare const SPR_SHLL: number
declare const SPR_PUMA: number
declare const SPR_HAMM: number
declare const SPR_KOOP: number
declare const SPR_BFLM: number
declare const SPR_MAXE: number
declare const SPR_MUS1: number
declare const SPR_MUS2: number
declare const SPR_TOAD: number
declare const SPR_NDRN: number
declare const SPR_NSPK: number
declare const SPR_NBMP: number
declare const SPR_HOOP: number
declare const SPR_NSCR: number
declare const SPR_NPRU: number
declare const SPR_CAPS: number
declare const SPR_IDYA: number
declare const SPR_NTPN: number
declare const SPR_SHLP: number
declare const SPR_PENG: number
declare const SPR_POPH: number
declare const SPR_HIVE: number
declare const SPR_BUMB: number
declare const SPR_BBUZ: number
declare const SPR_FMCE: number
declare const SPR_HMCE: number
declare const SPR_CACO: number
declare const SPR_BAL2: number
declare const SPR_SBOB: number
declare const SPR_SBFL: number
declare const SPR_SBSK: number
declare const SPR_HBAT: number
declare const SPR_SPRK: number
declare const SPR_BOM1: number
declare const SPR_BOM2: number
declare const SPR_BOM3: number
declare const SPR_BOM4: number
declare const SPR_BMNB: number
declare const SPR_ROIA: number
declare const SPR_ROIB: number
declare const SPR_ROIC: number
declare const SPR_ROID: number
declare const SPR_ROIE: number
declare const SPR_ROIF: number
declare const SPR_ROIG: number
declare const SPR_ROIH: number
declare const SPR_ROII: number
declare const SPR_ROIJ: number
declare const SPR_ROIK: number
declare const SPR_ROIL: number
declare const SPR_ROIM: number
declare const SPR_ROIN: number
declare const SPR_ROIO: number
declare const SPR_ROIP: number
declare const SPR_GFZD: number
declare const SPR_BRIC: number
declare const SPR_WDDB: number
declare const SPR_GWLG: number
declare const SPR_GWLR: number