declare const TOL_SP: number
declare const TOL_COOP: number
declare const TOL_COMPETITION: number
declare const TOL_RACE: number
declare const TOL_MATCH: number
declare const TOL_TAG: number
declare const TOL_CTF: number
declare const TOL_CUSTOM: number
declare const TOL_2D: number
declare const TOL_MARIO: number
declare const TOL_NIGHTS: number
declare const TOL_ERZ3: number
declare const TOL_XMAS: number