declare const tr_trans10: number
declare const tr_trans20: number
declare const tr_trans30: number
declare const tr_trans40: number
declare const tr_trans50: number
declare const tr_trans60: number
declare const tr_trans70: number
declare const tr_trans80: number
declare const tr_trans90: number
declare const NUMTRANSMAPS: number