declare const TR_TRANS10: number
declare const TR_TRANS20: number
declare const TR_TRANS30: number
declare const TR_TRANS40: number
declare const TR_TRANS50: number
declare const TR_TRANS60: number
declare const TR_TRANS70: number
declare const TR_TRANS80: number
declare const TR_TRANS90: number