declare const TRANS10: number
declare const TRANS20: number
declare const TRANS30: number
declare const TRANS40: number
declare const TRANS50: number
declare const TRANS60: number
declare const TRANS70: number
declare const TRANS80: number
declare const TRANS90: number