declare const gamemap: number
declare const maptol: number
declare const gamestate: number
declare const ultimatemode: boolean
declare const mariomode: boolean
declare const twodlevel: boolean
declare const circuitmap: boolean
declare var stoppedclock: boolean
declare const netgame: boolean
declare const multiplayer: boolean
declare const modeattacking: boolean
declare const splitscreen: boolean
declare const gamecomplete: boolean
declare const marathonmode: number
declare const devparm: boolean
declare const modifiedgame: boolean
declare const menuactive: boolean
declare const paused: boolean
declare var bluescore: number
declare var redscore: number
declare const timelimit: number
declare const pointlimit: number
declare const spstage_start: number
declare const spmarathon_start: number
declare const sstage_start: number
declare const sstage_end: number
declare const smpstage_start: number
declare const smpstage_end: number
declare const titlemap: number
declare const titlemapinaction: boolean
declare const bootmap: number
declare const tutorialmap: number
declare const tutorialmode: boolean
declare var skincolor_redteam: number
declare var skincolor_blueteam: number
declare var skincolor_redring: number
declare var skincolor_bluering: number
declare const invulntics: number
declare const sneakertics: number
declare const flashingtics: number
declare const tailsflytics: number
declare const underwatertics: number
declare const spacetimetics: number
declare const extralifetics: number
declare const nightslinktics: number
declare const gameovertics: number
declare const ammoremovaltics: number
declare const gametype: number
declare const gametyperules: number
declare const leveltime: number
declare const sstimer: number
declare const curWeather: number
declare const globalweather: number
declare const levelskynum: number
declare const globallevelskynum: number
declare var mapmusname: string
declare var mapmusflags: number
declare const mapmusposition: number
declare const consoleplayer: player_t
declare var displayplayer: player_t
declare const secondarydisplayplayer: player_t
declare const isserver: boolean
declare const isdedicatedserver: boolean
declare const server: player_t
declare var emeralds: number
declare var token: number
declare var gravity: number
declare const _G: any
declare const VERSION: number
declare const SUBVERSION: number
declare const VERSIONSTRING: string
declare const mouse: mouse_t
declare const mouse1: mouse_t

declare const mobjinfo: {[key in MobjTypes]: mobjinfo_t}
declare const states: {[key in States]: state_t}
declare const sfxinfo: {[key in Sounds]: sfxinfo_t}
declare const sprnames: {[key: number | string]: string | number}
declare const players: player_t[]
declare const skins: {[key: number | string]: skin_t}
declare const mapthings: mapthing_t[]
declare const vertexes: vertex_t[]
declare const lines: line_t[]
declare const sides: side_t[]
declare const subsectors: subsector_t[]
declare const sectors: sector_t[]
declare const mapheaderinfo: mapheader_t[]
declare const hudinfo: {[key in HUDItems]: spriteinfo_t}
declare const spriteinfo: {[key in Sprites]: spriteframepivot_t[]}
declare const spr2defaults: Sprites[]
declare const gamekeydown: boolean[]