
 /** @compileMembersOnly */
declare enum  LevelFlags
{
    LF_SCRIPTISFILE,
    LF_SPEEDMUSIC,
    LF_NOSSMUSIC,
    LF_NORELOAD,
    LF_NOZONE,
    LF_SAVEGAME,
    LF_MIXNIGHTSCOUNTDOWN,
    LF_WARNINGTITLE,
    LF_NOTITLECARD,
    LF2_HIDEINMENU,
    LF2_HIDEINSTATS,
    LF2_RECORDATTACK,
    LF2_NIGHTSATTACK,
    LF2_NOVISITNEEDED,
    LF2_WIDEICON,
}