
 /** @compileMembersOnly */
declare enum  RenderFlags
{
    RF_HORIZONTALFLIP,
    RF_VERTICALFLIP,
    RF_ABSOLUTEOFFSETS,
    RF_FLIPOFFSETS,
    RF_SPLATMASK,
    RF_SLOPESPLAT,
    RF_OBJECTSLOPESPLAT,
    RF_NOSPLATBILLBOARD,
    RF_NOSPLATROLLANGLE,
    RF_BLENDMASK,
    RF_FULLBRIGHT,
    RF_FULLDARK,
    RF_NOCOLORMAPS,
    RF_SPRITETYPEMASK,
    RF_PAPERSPRITE,
    RF_FLOORSPRITE,
    RF_SHADOWDRAW,
    RF_SHADOWEFFECTS,
    RF_DROPSHADOW
}