
 /** @compileMembersOnly */
declare enum  HUDItems
{
    HUD_LIVES,
    HUD_RINGS,
    HUD_RINGSNUM,
    HUD_RINGSNUMTICS,
    HUD_SCORE,
    HUD_SCORENUM,
    HUD_TIME,
    HUD_MINUTES,
    HUD_TIMECOLON,
    HUD_SECONDS,
    HUD_TIMETICCOLON,
    HUD_TICS,
    HUD_HUNTPICS,
    HUD_POWERUPS,
    HUD_SS_TOTALRINGS,
    HUD_GETRINGS,
    HUD_GETRINGSNUM,
    HUD_TIMELEFT,
    HUD_TIMELEFTNUM,
    HUD_TIMEUP,
}