
 /** @compileMembersOnly */
declare enum  PolyObjectFlags
{
    POF_CLIPLINES,
    POF_CLIPPLANES,
    POF_SOLID,
    POF_TESTHEIGHT,
    POF_RENDERSIDES,
    POF_RENDERTOP,
    POF_RENDERBOTTOM,
    POF_RENDERPLANES,
    POF_RENDERALL,
    POF_INVERT,
    POF_INVERTPLANES,
    POF_INVERTPLANESONLY,
    POF_PUSHABLESTOP,
    POF_LDEXEC,
    POF_ONESIDE,
    POF_NOSPECIALS,
    POF_SPLAT
}