
 /** @compileMembersOnly */
declare enum  SkinFlags
{
    SF_SUPER,
    SF_NOSUPERSPIN,
    SF_NOSPINDASHDUST,
    SF_HIRES,
    SF_NOSKID,
    SF_NOSPEEDADJUST,
    SF_RUNONWATER,
    SF_NOJUMPSPIN,
    SF_NOJUMPDAMAGE,
    SF_STOMPDAMAGE,
    SF_MARIODAMAGE,
    SF_MACHINE,
    SF_DASHMODE,
    SF_FASTEDGE,
    SF_MULTIABILITY,
    SF_NONIGHTSROTATION,
    SF_NONIGHTSSUPER,
    SF_NOSUPERSPRITES,
    SF_NOSUPERJUMPBOOST,
    SF_CANBUSTWALLS,
    SF_NOSHIELDABILITY
}