declare const sectors: sector_t[]
declare const subsectors: subsector_t[]
declare const lines: line_t[]
declare const sides: side_t[]
declare const vertexes: vertex_t[]
declare const segs: seg_t[]
declare const nodes: node_t[]
declare const mapheaderinfo: mapheader_t[]