declare interface player_t
{
    readonly valid: boolean
    readonly name: string
    mo: mobj_t
    realmo: mobj_t
    cmd: ticcmd_t
    playerstate: PlayerStates
    camerascale: fixed_t
    shieldscale: fixed_t
    viewz: fixed_t
    viewheight: fixed_t
    deltaviewheight: fixed_t
    bob: fixed_t
    viewrollangle: angle_t
    aiming: angle_t
    drawangle: angle_t
    rings: INT16
    spheres: INT16
    pity: SINT8
    currentweapon: INT32
    ringweapons: INT32
    ammoremoval: UINT16
    ammoremovaltimer: tic_t
    ammoremovalweapon: INT32
    readonly powers: PowersArray
    pflags: PlayerFlags
    panim: PlayerAnimations
    flashcount: UINT16
    flashpal: UINT16
    skincolor: SkinColors
    score: UINT32
    dashmode: tic_t
    dashspeed: fixed_t
    normalspeed: fixed_t
    runspeed: fixed_t
    thrustfactor: fixed_t
    accelstart: fixed_t
    acceleration: fixed_t
    charability: UINT8
    charability2: UINT8
    charflags: UINT32
    thokitem: MobjTypes
    spinitem: MobjTypes
    revitem: MobjTypes
    followitem: MobjTypes
    followmobj: mobj_t
    actionspd: fixed_t
    mindash: fixed_t
    maxdash: fixed_t
    jumpfactor: fixed_t
    height: fixed_t
    spinheight: fixed_t
    lives: SINT8
    continues: SINT8
    xtralife: SINT8
    gotcontinue: UINT8
    speed: fixed_t
    secondjump: UINT8
    fly1: UINT8
    scoreadd: UINT8
    glidetime: tic_t
    climbing: UINT8
    deadtime: INT32
    exiting: tic_t
    homing: UINT8
    skidtime: tic_t
    cmomx: fixed_t
    cmomy: fixed_t
    rmomx: fixed_t
    rmomy: fixed_t
    numboxes: INT16
    totalring: INT16
    realtime: tic_t
    laps: UINT8
    ctfteam: INT32
    gotflag: UINT16
    weapondelay: INT32
    tossdelay: INT32
    starpostx: INT16
    starposty: INT16
    starpostz: INT16
    starpostnum: INT32
    starposttime: tic_t
    starpostangle: angle_t
    starpostscale: fixed_t
    angle_pos: angle_t
    old_angle_pos: angle_t
    axis1: mobj_t
    axis2: mobj_t
    bumpertime: tic_t
    flyangle: INT32
    drilltimer: tic_t
    linkcount: INT32
    linktimer: tic_t
    anotherflyangle: INT32
    nightstime: tic_t
    drillmeter: INT32
    drilldelay: tic_t
    bonustime: boolean
    capsule: mobj_t
    drone: mobj_t
    oldscale: fixed_t
    mare: UINT8
    marelap: UINT8
    marebonuslap: UINT8
    marebegunat: tic_t
    startedtime: tic_t
    finishedtime: tic_t
    finishedrings: INT16
    marescore: UINT32
    lastmarescore: UINT32
    totalmarescore: UINT32
    lastmare: UINT8
    lastmarelap: UINT8
    lastmarebonuslap: UINT8
    totalmarelap: UINT8
    totalmarebonuslap: UINT8
    maxlink: INT32
    texttimer: UINT8
    textvar: UINT8
    lastsidehit: INT16
    lastlinehit: INT16
    losstime: tic_t
    timeshit: UINT8
    onconveyor: INT32
    awayviewmobj: mobj_t
    awayviewtics: INT32
    awayviewaiming: angle_t
    spectator: boolean
    outofcoop: boolean
    readonly bot: BotType
    blocked: boolean
    lastbuttons: UINT16
    botleader: player_t
    jointime: tic_t
    quittime: tic_t
    fovadd: fixed_t
    [key: string]: any
}